import { Router } from 'express';
import {
  CARDIO_EXERCISES,
  EXERCISES,
  EXERCISE_BY_ID,
  MAX_EXERCISES_PER_MUSCLE,
  MUSCLE_GROUPS,
} from '@getfit/shared';
import { requireAuth, type AuthenticatedRequest } from '../middleware/auth';
import { requireSubscription } from '../middleware/subscriptionGate';
import { asyncHandler, validateBody } from '../middleware/validate';
import { userRepository } from '../repositories/userRepository';
import { ExerciseSelectionService } from '../services/exerciseSelectionService';
import { programService } from '../services/programService';
import { userService } from '../services/userService';
import { errors } from '../utils/errors';
import { preferencesSchema } from './schemas';

export const exerciseRoutes = Router();
const selection = new ExerciseSelectionService();

/** The full library. Cached hard by the client for offline use. */
exerciseRoutes.get('/library', (_req, res) => {
  res.set('Cache-Control', 'public, max-age=86400');
  res.json({
    muscleGroups: MUSCLE_GROUPS,
    exercises: EXERCISES,
    cardio: CARDIO_EXERCISES,
  });
});

exerciseRoutes.get('/:exerciseId', (req, res, next) => {
  const exercise = EXERCISE_BY_ID[req.params.exerciseId];
  if (!exercise) {
    next(errors.notFound('That exercise is not in the library.'));
    return;
  }
  res.json({ exercise });
});

/** The four choices per muscle shown on the Exercise Preferences screen. */
exerciseRoutes.get(
  '/preferences/choices',
  requireAuth,
  asyncHandler<AuthenticatedRequest>(async (req, res) => {
    const profile = await userRepository.getProfile(req.userId);
    if (!profile) throw errors.invalidInput('Complete onboarding first.');

    const [goals, equipment, saved] = await Promise.all([
      userRepository.getGoals(req.userId),
      programService.resolveEquipment(req.userId, profile),
      userRepository.getPreferences(req.userId),
    ]);

    const choiceSets = selection.buildChoiceSets({
      location: profile.trainingLocation,
      equipment,
      level: profile.trainingLevel,
      goals: goals.map((g) => g.goalType),
    });

    res.json({
      maxPerMuscle: MAX_EXERCISES_PER_MUSCLE,
      muscleGroups: MUSCLE_GROUPS,
      choiceSets,
      saved,
    });
  }),
);

/** "Generate for me" — the AI chooses and saves the selection itself. */
exerciseRoutes.post(
  '/preferences/generate',
  requireAuth,
  requireSubscription,
  asyncHandler<AuthenticatedRequest>(async (req, res) => {
    const profile = await userRepository.getProfile(req.userId);
    if (!profile) throw errors.invalidInput('Complete onboarding first.');

    const [goals, equipment] = await Promise.all([
      userRepository.getGoals(req.userId),
      programService.resolveEquipment(req.userId, profile),
    ]);

    const preferences = selection.generatePreferences({
      location: profile.trainingLocation,
      equipment,
      level: profile.trainingLevel,
      goals: goals.map((g) => g.goalType),
    });

    const saved = await userRepository.setPreferences(req.userId, preferences);
    res.json({ preferences: saved, autoGenerated: true });
  }),
);

/**
 * Saves a manual selection. Whatever is stored here is exactly what the program
 * generator may use — nothing is substituted behind the user's back.
 */
exerciseRoutes.put(
  '/preferences',
  requireAuth,
  requireSubscription,
  validateBody(preferencesSchema),
  asyncHandler<AuthenticatedRequest>(async (req, res) => {
    const profile = await userRepository.getProfile(req.userId);
    if (!profile) throw errors.invalidInput('Complete onboarding first.');

    const [goals, equipment] = await Promise.all([
      userRepository.getGoals(req.userId),
      programService.resolveEquipment(req.userId, profile),
    ]);

    const body = req.body as typeof preferencesSchema._output;
    const validated = selection.validatePreferences(
      body.preferences.map((p) => ({
        muscleGroup: p.muscleGroup as never,
        exerciseIds: p.exerciseIds,
        autoGenerated: false,
      })),
      {
        location: profile.trainingLocation,
        equipment,
        level: profile.trainingLevel,
        goals: goals.map((g) => g.goalType),
      },
    );

    const saved = await userRepository.setPreferences(req.userId, validated);
    res.json({ preferences: saved, autoGenerated: false });
  }),
);

/** Changing preferences after onboarding rebuilds future training. */
exerciseRoutes.put(
  '/preferences/apply',
  requireAuth,
  requireSubscription,
  validateBody(preferencesSchema),
  asyncHandler<AuthenticatedRequest>(async (req, res) => {
    const profile = await userRepository.getProfile(req.userId);
    if (!profile) throw errors.invalidInput('Complete onboarding first.');

    const [goals, equipment] = await Promise.all([
      userRepository.getGoals(req.userId),
      programService.resolveEquipment(req.userId, profile),
    ]);

    const body = req.body as typeof preferencesSchema._output;
    const validated = selection.validatePreferences(
      body.preferences.map((p) => ({
        muscleGroup: p.muscleGroup as never,
        exerciseIds: p.exerciseIds,
        autoGenerated: false,
      })),
      {
        location: profile.trainingLocation,
        equipment,
        level: profile.trainingLevel,
        goals: goals.map((g) => g.goalType),
      },
    );

    const saved = await userService.updatePreferences(req.userId, validated);
    res.json({ preferences: saved, programRegenerated: true });
  }),
);
