import assert from 'node:assert/strict';
import { test } from 'node:test';
import {
  EXERCISE_BY_ID,
  EXERCISE_CHOICES_PER_MUSCLE,
  MAX_EXERCISES_PER_MUSCLE,
  MUSCLE_GROUP_IDS,
  isExerciseAvailable,
  type EquipmentId,
} from '../src/index';
import { ExerciseSelectionService } from '../src/index';
import { AppError } from '../src/errors';
import { selectionContext } from './helpers';

const service = new ExerciseSelectionService();

test('offers four choices for every muscle group in a gym', () => {
  const sets = service.buildChoiceSets(selectionContext());
  assert.equal(sets.length, MUSCLE_GROUP_IDS.length);

  for (const set of sets) {
    assert.equal(
      set.choices.length,
      EXERCISE_CHOICES_PER_MUSCLE,
      `${set.muscleGroup} should offer four choices`,
    );
    for (const choice of set.choices) {
      assert.equal(choice.primaryMuscle, set.muscleGroup);
    }
  }
});

test('choices only include exercises the user can actually perform', () => {
  const equipment: EquipmentId[] = ['bodyweight', 'dumbbells', 'bench'];
  const sets = service.buildChoiceSets(selectionContext({ location: 'home', equipment }));

  for (const set of sets) {
    for (const choice of set.choices) {
      assert.notEqual(choice.availability, 'gym', `${choice.name} is gym-only`);
      assert.ok(
        isExerciseAvailable(choice, 'home', equipment),
        `${choice.name} needs equipment the user does not have`,
      );
      // Support gear cannot be substituted, so a rack or pull-up bar must be owned.
      for (const item of choice.equipment) {
        if (['squat_rack', 'pullup_bar', 'dip_station'].includes(item)) {
          assert.fail(`${choice.name} requires ${item}`);
        }
      }
    }
  }
});

test('every realistic home setup still offers four choices per muscle', () => {
  const setups: EquipmentId[][] = [
    ['bodyweight'],
    ['bodyweight', 'resistance_bands'],
    ['bodyweight', 'dumbbells'],
    ['bodyweight', 'kettlebell'],
    ['bodyweight', 'pullup_bar'],
    ['bodyweight', 'dumbbells', 'bench'],
  ];

  for (const equipment of setups) {
    const sets = service.buildChoiceSets(selectionContext({ location: 'home', equipment }));
    for (const set of sets) {
      assert.equal(
        set.choices.length,
        EXERCISE_CHOICES_PER_MUSCLE,
        `${set.muscleGroup} with [${equipment.join(', ')}] offered ${set.choices.length} choices`,
      );
      assert.equal(
        set.limitedByEquipment,
        false,
        `${set.muscleGroup} with [${equipment.join(', ')}] reported as equipment-limited`,
      );
    }
  }
});

test('flags muscles where equipment genuinely limits the available choices', () => {
  // Degenerate setup: a gym user owning nothing rules out the home-improvised
  // movements (towel, door frame) that carry the bodyweight-only case.
  const sets = service.buildChoiceSets(selectionContext({ location: 'gym', equipment: ['bodyweight'] }));
  const biceps = sets.find((s) => s.muscleGroup === 'biceps');
  assert.ok(biceps);
  assert.ok(biceps.choices.length < EXERCISE_CHOICES_PER_MUSCLE);
  assert.equal(biceps.limitedByEquipment, true);
});

test('generate for me picks at most three exercises per muscle', () => {
  const preferences = service.generatePreferences(selectionContext());
  assert.equal(preferences.length, MUSCLE_GROUP_IDS.length);

  for (const preference of preferences) {
    assert.ok(preference.exerciseIds.length > 0);
    assert.ok(preference.exerciseIds.length <= MAX_EXERCISES_PER_MUSCLE);
    assert.equal(preference.autoGenerated, true);
    for (const id of preference.exerciseIds) {
      assert.equal(EXERCISE_BY_ID[id].primaryMuscle, preference.muscleGroup);
    }
  }
});

test('generate for me keeps beginners to two exercises per muscle', () => {
  const preferences = service.generatePreferences(selectionContext({ level: 'beginner' }));
  for (const preference of preferences) {
    assert.ok(preference.exerciseIds.length <= 2, `${preference.muscleGroup} exceeded two`);
  }
});

test('rejects more than three exercises for one muscle', () => {
  assert.throws(
    () =>
      service.validatePreferences(
        [
          {
            muscleGroup: 'chest',
            exerciseIds: ['bench_press', 'incline_bench_press', 'dumbbell_fly', 'cable_fly'],
            autoGenerated: false,
          },
        ],
        selectionContext(),
      ),
    (error: unknown) =>
      error instanceof AppError && /up to 3 exercises/i.test(error.message),
  );
});

test('rejects an exercise that does not train the selected muscle', () => {
  assert.throws(
    () =>
      service.validatePreferences(
        [{ muscleGroup: 'chest', exerciseIds: ['barbell_curl'], autoGenerated: false }],
        selectionContext(),
      ),
    (error: unknown) => error instanceof AppError && /does not train/i.test(error.message),
  );
});

test('rejects an exercise the user lacks equipment for', () => {
  assert.throws(
    () =>
      service.validatePreferences(
        [{ muscleGroup: 'chest', exerciseIds: ['cable_fly'], autoGenerated: false }],
        selectionContext({ location: 'home', equipment: ['bodyweight'] }),
      ),
    (error: unknown) => error instanceof AppError && /equipment/i.test(error.message),
  );
});

test('rejects duplicate exercises and duplicate muscle entries', () => {
  assert.throws(() =>
    service.validatePreferences(
      [{ muscleGroup: 'chest', exerciseIds: ['bench_press', 'bench_press'], autoGenerated: false }],
      selectionContext(),
    ),
  );
  assert.throws(() =>
    service.validatePreferences(
      [
        { muscleGroup: 'chest', exerciseIds: ['bench_press'], autoGenerated: false },
        { muscleGroup: 'chest', exerciseIds: ['push_up'], autoGenerated: false },
      ],
      selectionContext(),
    ),
  );
});

test('a manual selection is the only pool the generator may draw from', () => {
  const { pool, userChosen } = service.resolvePool(
    'chest',
    [{ muscleGroup: 'chest', exerciseIds: ['push_up'], autoGenerated: false }],
    selectionContext(),
  );
  assert.equal(userChosen, true);
  assert.deepEqual(pool.map((e) => e.id), ['push_up']);
});

test('muscles the user left empty are filled by the AI', () => {
  const { pool, userChosen } = service.resolvePool('back', [], selectionContext());
  assert.equal(userChosen, false);
  assert.ok(pool.length > 0);
  assert.ok(pool.every((e) => e.primaryMuscle === 'back'));
});
