import assert from 'node:assert/strict';
import { test } from 'node:test';
import {
  EXERCISE_BY_ID,
  MAJOR_MUSCLE_GROUPS,
  MAX_CARDIO_MINUTES,
  MAX_WARMUP_SETS,
  SESSION_DURATIONS,
  TRAINING_DAY_OPTIONS,
  type GoalType,
  type SessionDuration,
  type TrainingDays,
} from '../src/index';
import { ExerciseSelectionService } from '../src/index';
import { ProgramGenerationService } from '../src/index';
import { baseCardioMinutes } from '../src/index';
import { programInput, selectionContext } from './helpers';

const generator = new ProgramGenerationService();
const selection = new ExerciseSelectionService();

test('produces the right split for every training-day count', () => {
  const expected: Record<number, string[]> = {
    1: ['Full Body'],
    2: ['Full Body A', 'Full Body B'],
    3: ['Full Body A', 'Full Body B', 'Full Body C'],
    4: ['Upper Body', 'Lower Body', 'Upper Body', 'Lower Body'],
    6: ['Push', 'Pull', 'Legs', 'Push', 'Pull', 'Legs'],
  };

  for (const days of TRAINING_DAY_OPTIONS) {
    const program = generator.generate(
      programInput({ profile: { trainingDays: days } as never }),
    );
    assert.equal(program.days.length, days, `${days} days requested`);
    if (expected[days]) {
      assert.deepEqual(program.days.map((d) => d.focus), expected[days]);
    }
  }
});

test('every generated session fits the selected duration', () => {
  for (const days of TRAINING_DAY_OPTIONS) {
    for (const duration of SESSION_DURATIONS) {
      const program = generator.generate(
        programInput({
          profile: { trainingDays: days, sessionDurationMinutes: duration } as never,
        }),
      );
      for (const day of program.days) {
        assert.ok(
          day.durationMinutes <= duration,
          `${days}d/${duration}min: ${day.focus} ran to ${day.durationMinutes} minutes`,
        );
        assert.ok(day.exercises.length >= 1, `${days}d/${duration}min: ${day.focus} was empty`);
      }
    }
  }
});

test('four or more training days trains each major muscle at least twice', () => {
  for (const days of [4, 5, 6] as TrainingDays[]) {
    const program = generator.generate(programInput({ profile: { trainingDays: days } as never }));

    const frequency = new Map<string, number>();
    for (const day of program.days) {
      const trained = new Set(
        day.exercises.map((e) => EXERCISE_BY_ID[e.exerciseId]?.primaryMuscle).filter(Boolean),
      );
      for (const muscle of trained) {
        frequency.set(muscle as string, (frequency.get(muscle as string) ?? 0) + 1);
      }
    }

    for (const muscle of MAJOR_MUSCLE_GROUPS) {
      assert.ok(
        (frequency.get(muscle) ?? 0) >= 2,
        `${days} days: ${muscle} trained ${frequency.get(muscle) ?? 0} times`,
      );
    }
  }
});

test('only uses exercises the user selected in preferences', () => {
  const preferences = [
    { muscleGroup: 'chest' as const, exerciseIds: ['push_up'], autoGenerated: false },
    { muscleGroup: 'back' as const, exerciseIds: ['dumbbell_row'], autoGenerated: false },
  ];

  const program = generator.generate(programInput({ exercisePreferences: preferences }));

  for (const day of program.days) {
    for (const entry of day.exercises) {
      const exercise = EXERCISE_BY_ID[entry.exerciseId];
      if (exercise.primaryMuscle === 'chest') assert.equal(entry.exerciseId, 'push_up');
      if (exercise.primaryMuscle === 'back') assert.equal(entry.exerciseId, 'dumbbell_row');
    }
  }
});

test('never prescribes equipment a home user does not own', () => {
  const equipment = ['bodyweight', 'dumbbells', 'bench'] as never;
  const program = generator.generate(
    programInput({
      profile: { trainingLocation: 'home' } as never,
      equipment,
      exercisePreferences: selection.generatePreferences(
        selectionContext({ location: 'home', equipment }),
      ),
    }),
  );

  const owned = new Set<string>(['bodyweight', 'dumbbells', 'bench']);
  for (const day of program.days) {
    for (const entry of day.exercises) {
      const exercise = EXERCISE_BY_ID[entry.exerciseId];
      assert.notEqual(exercise.availability, 'gym', `${exercise.name} is gym-only`);
      const hasAlternative = exercise.equipment.some((item) => owned.has(item));
      assert.ok(hasAlternative || exercise.equipment.length === 0, `${exercise.name} is not trainable`);
    }
  }
});

test('caps warm-ups at two and only on the leading compounds', () => {
  const program = generator.generate(programInput());

  for (const day of program.days) {
    let warmupExercises = 0;
    for (const entry of day.exercises) {
      assert.ok(entry.warmupSets <= MAX_WARMUP_SETS, 'more than two warm-up sets prescribed');
      if (entry.warmupSets > 0) {
        warmupExercises += 1;
        assert.ok(EXERCISE_BY_ID[entry.exerciseId].isCompound, 'warm-ups on an isolation exercise');
      }
    }
    assert.ok(warmupExercises <= 2, 'warm-ups spread across too many exercises');
  }
});

test('uses the default rep bands and adapts them to a strength goal', () => {
  const hypertrophy = generator.generate(programInput({ goals: ['muscle_gain'] }));
  for (const day of hypertrophy.days) {
    for (const entry of day.exercises) {
      const exercise = EXERCISE_BY_ID[entry.exerciseId];
      if (exercise.isTimed || exercise.isBodyweight) continue;
      if (exercise.isCompound) {
        assert.deepEqual([entry.repsMin, entry.repsMax], [6, 10], exercise.name);
      } else {
        assert.deepEqual([entry.repsMin, entry.repsMax], [10, 15], exercise.name);
      }
    }
  }

  const strength = generator.generate(programInput({ goals: ['strength'] }));
  const compound = strength.days
    .flatMap((d) => d.exercises)
    .find((e) => EXERCISE_BY_ID[e.exerciseId].isCompound && !EXERCISE_BY_ID[e.exerciseId].isBodyweight);
  assert.ok(compound);
  assert.deepEqual([compound.repsMin, compound.repsMax], [4, 6]);
});

test('compounds are ordered before isolation work, and abs come last', () => {
  const program = generator.generate(programInput());

  for (const day of program.days) {
    let seenIsolation = false;
    for (const entry of day.exercises) {
      const exercise = EXERCISE_BY_ID[entry.exerciseId];
      if (!exercise.isCompound) seenIsolation = true;
      else assert.ok(!seenIsolation, `${exercise.name} came after isolation work`);
    }
    const absIndex = day.exercises.findIndex((e) => EXERCISE_BY_ID[e.exerciseId].primaryMuscle === 'abs');
    if (absIndex >= 0) assert.equal(absIndex, day.exercises.length - 1, 'abs were not last');
  }
});

test('prescribes conservative starting weights scaled by training level', () => {
  // Pin the chest selection so both programs are compared on the same lift.
  const preferences = [
    { muscleGroup: 'chest' as const, exerciseIds: ['bench_press'], autoGenerated: false },
  ];
  const beginner = generator.generate(
    programInput({ profile: { trainingLevel: 'beginner' } as never, exercisePreferences: preferences }),
  );
  const advanced = generator.generate(
    programInput({ profile: { trainingLevel: 'advanced' } as never, exercisePreferences: preferences }),
  );

  const benchOf = (program: typeof beginner) =>
    program.days.flatMap((d) => d.exercises).find((e) => e.exerciseId === 'bench_press');

  const beginnerBench = benchOf(beginner);
  const advancedBench = benchOf(advanced);
  assert.ok(beginnerBench?.startingWeight);
  assert.ok(advancedBench?.startingWeight);
  assert.ok(
    beginnerBench.startingWeight < advancedBench.startingWeight,
    'a beginner should start lighter than an advanced lifter',
  );
  assert.ok(beginnerBench.startingWeight >= 20, 'never lighter than an empty bar');
});

test('reuses real performance history for starting weight', () => {
  const program = generator.generate(
    programInput({ previousPerformance: { bench_press: 92.5 } }),
  );
  const bench = program.days.flatMap((d) => d.exercises).find((e) => e.exerciseId === 'bench_press');
  assert.equal(bench?.startingWeight, 92.5);
});

test('bodyweight exercises are prescribed without a weight', () => {
  const equipment = ['bodyweight'] as never;
  const program = generator.generate(
    programInput({
      profile: { trainingLocation: 'home' } as never,
      equipment,
      exercisePreferences: selection.generatePreferences(
        selectionContext({ location: 'home', equipment }),
      ),
    }),
  );

  for (const day of program.days) {
    for (const entry of day.exercises) {
      const exercise = EXERCISE_BY_ID[entry.exerciseId];
      if (exercise.loadFactor === undefined) {
        assert.equal(entry.startingWeight, null, `${exercise.name} was given a weight`);
      }
    }
  }
});

test('cardio never exceeds fifteen minutes and falls as body fat improves', () => {
  const minutesAt = (bodyFatPercent: number): number => {
    const program = generator.generate(
      programInput({ goals: ['fat_loss'], bodyMetrics: { bodyFatPercent, muscleMassKg: 60 } }),
    );
    return Math.max(...program.days.map((d) => d.cardio?.minutes ?? 0));
  };

  const high = minutesAt(32);
  const mid = minutesAt(24);
  const low = minutesAt(14);

  assert.ok(high <= MAX_CARDIO_MINUTES, 'cardio exceeded the cap');
  assert.ok(high >= mid, `cardio should not rise as body fat falls (${high} vs ${mid})`);
  assert.ok(mid >= low, `cardio should not rise as body fat falls (${mid} vs ${low})`);
  assert.ok(low < high, 'leaner users should get less cardio');
});

test('cardio hits the specified duration at every body-fat anchor', () => {
  // The product spec fixes these four points. A goal must not move them — a
  // fat-loss bonus once pinned 27% and 24% both to the cap, so the user saw no
  // change for real progress.
  const anchors: Array<[number, number]> = [
    [27, 15],
    [24, 12],
    [21, 8],
    [18, 5],
  ];
  const goalSets: GoalType[][] = [
    ['muscle_gain'],
    ['fat_loss'],
    ['strength'],
    ['general_fitness'],
    ['recomposition'],
  ];

  for (const goals of goalSets) {
    for (const [bodyFatPercent, expected] of anchors) {
      assert.equal(
        baseCardioMinutes(bodyFatPercent, goals),
        expected,
        `${goals.join('+')} at ${bodyFatPercent}% body fat should get ${expected} minutes`,
      );
    }

    // And it never rises as the user gets leaner.
    const series = [32, 27, 24, 21, 18, 15, 12].map((bf) => baseCardioMinutes(bf, goals));
    for (let i = 1; i < series.length; i += 1) {
      assert.ok(
        series[i] <= series[i - 1],
        `${goals.join('+')} cardio rose as body fat fell: ${series.join(' -> ')}`,
      );
    }
  }
});

test('computes direct, secondary and effective weekly volume', () => {
  const program = generator.generate(programInput());
  const chest = program.volumeSummary.chest;

  assert.ok(chest.directSets > 0, 'no direct chest volume');
  assert.ok(chest.secondarySets > 0, 'pressing should pay into chest indirectly too');
  assert.equal(
    Math.round(chest.effectiveSets * 10) / 10,
    Math.round((chest.directSets + chest.secondarySets) * 10) / 10,
  );

  // Pressing volume must be charged to the triceps even with no direct work.
  assert.ok(program.volumeSummary.triceps.secondarySets > 0);
});

test('keeps weekly volume inside a sane band rather than stacking overlap', () => {
  const program = generator.generate(
    programInput({ profile: { trainingDays: 6, sessionDurationMinutes: 60 } as never }),
  );
  for (const [muscle, entry] of Object.entries(program.volumeSummary)) {
    assert.ok(entry.effectiveSets <= 34, `${muscle} reached ${entry.effectiveSets} effective sets`);
  }
});

test('warm-up sets ramp below the working weight', () => {
  const program = generator.generate(programInput());
  const withWarmup = program.days
    .flatMap((d) => d.exercises)
    .find((e) => e.warmupSets > 0 && e.startingWeight);
  assert.ok(withWarmup);

  const warmups = withWarmup.prescribedSets.filter((s) => s.isWarmup);
  const working = withWarmup.prescribedSets.filter((s) => !s.isWarmup);
  assert.equal(warmups.length, withWarmup.warmupSets);
  assert.equal(working.length, withWarmup.sets);
  for (const set of warmups) {
    assert.ok((set.prescribedWeight ?? 0) < (withWarmup.startingWeight ?? 0));
  }
  for (const set of working) {
    assert.equal(set.prescribedWeight, withWarmup.startingWeight);
  }
});

test('a fifteen minute session still produces a usable workout', () => {
  const program = generator.generate(
    programInput({ profile: { sessionDurationMinutes: 15 as SessionDuration } as never }),
  );
  for (const day of program.days) {
    assert.ok(day.exercises.length >= 1);
    assert.ok(day.durationMinutes <= 15);
    for (const entry of day.exercises) {
      assert.equal(entry.warmupSets, 0, 'short sessions should not spend time on warm-ups');
    }
  }
});
