/**
 * GetFit — shared domain types.
 * Used by the API server and the mobile client so both sides agree on shapes.
 */

/* ------------------------------------------------------------------ */
/* Muscles & equipment                                                 */
/* ------------------------------------------------------------------ */

export type MuscleGroup =
  | 'chest'
  | 'back'
  | 'shoulders'
  | 'biceps'
  | 'triceps'
  | 'forearms'
  | 'quads'
  | 'hamstrings'
  | 'glutes'
  | 'calves'
  | 'abs';

export type SecondaryMuscle = MuscleGroup | 'traps' | 'lower_back' | 'rear_delts' | 'front_delts' | 'lats' | 'adductors' | 'hip_flexors' | 'obliques' | 'cardio';

export type EquipmentId =
  | 'bodyweight'
  | 'resistance_bands'
  | 'dumbbells'
  | 'adjustable_dumbbells'
  | 'kettlebell'
  | 'barbell'
  | 'weight_plates'
  | 'bench'
  | 'pullup_bar'
  | 'dip_station'
  | 'squat_rack'
  | 'cable_machine'
  | 'smith_machine'
  | 'resistance_machines'
  | 'treadmill'
  | 'stationary_bike'
  | 'rowing_machine'
  | 'elliptical'
  | 'ez_bar'
  | 'ab_wheel'
  | 'jump_rope'
  | 'medicine_ball'
  | 'stability_ball'
  | 'suspension_trainer'
  | 'step_platform';

/* ------------------------------------------------------------------ */
/* Exercises                                                           */
/* ------------------------------------------------------------------ */

export type ExerciseCategory =
  | 'push'
  | 'pull'
  | 'squat'
  | 'hinge'
  | 'lunge'
  | 'carry'
  | 'core'
  | 'isolation'
  | 'cardio';

export type Difficulty = 'beginner' | 'intermediate' | 'advanced';

export type Availability = 'home' | 'gym' | 'both';

export interface Exercise {
  id: string;
  name: string;
  primaryMuscle: MuscleGroup;
  /** Muscles that receive meaningful indirect stimulus. */
  secondaryMuscles: SecondaryMuscle[];
  equipment: EquipmentId[];
  availability: Availability;
  difficulty: Difficulty;
  /** Compound exercises cross multiple joints and count toward several muscles. */
  isCompound: boolean;
  category: ExerciseCategory;
  instructions: string;
  setup: string[];
  execution: string[];
  commonMistakes: string[];
  repRangeMin: number;
  repRangeMax: number;
  restSeconds: number;
  /** Key for the bundled vector illustration rendered by the mobile client. */
  illustration: string;
  /** Rough load factor vs. bodyweight, used to seed conservative starting weights. */
  loadFactor?: number;
  /** True when the movement is loaded by bodyweight rather than external weight. */
  isBodyweight?: boolean;
  /** Unilateral movements are prescribed per side. */
  isUnilateral?: boolean;
  /** Time-based movements (planks, carries, hangs) log seconds instead of reps. */
  isTimed?: boolean;
  /** Minutes of work per set for duration budgeting overrides. */
  tempoSecondsPerRep?: number;
}

/* ------------------------------------------------------------------ */
/* Profile / onboarding                                                */
/* ------------------------------------------------------------------ */

export type Sex = 'male' | 'female';
export type TrainingLevel = 'beginner' | 'intermediate' | 'advanced';
export type TrainingLocation = 'home' | 'gym';
export type GoalType = 'muscle_gain' | 'fat_loss' | 'recomposition' | 'strength' | 'general_fitness';
export type SessionDuration = 15 | 30 | 45 | 60;
export type TrainingDays = 1 | 2 | 3 | 4 | 5 | 6 | 7;

export interface UserProfile {
  userId: string;
  age: number;
  sex: Sex;
  heightCm: number;
  weightKg: number;
  trainingLevel: TrainingLevel;
  trainingLocation: TrainingLocation;
  trainingDays: TrainingDays;
  sessionDurationMinutes: SessionDuration;
  onboardingCompleted: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface UserGoal {
  id?: string;
  userId?: string;
  goalType: GoalType;
  /** Optional numeric target (e.g. target body-fat %, target weight, target lift). */
  targetValue?: number | null;
  targetUnit?: string | null;
  targetExerciseId?: string | null;
  startValue?: number | null;
  isActive?: boolean;
  createdAt?: string;
}

export interface ExercisePreference {
  muscleGroup: MuscleGroup;
  exerciseIds: string[];
  /** True when the AI picked these rather than the user. */
  autoGenerated: boolean;
}

/* ------------------------------------------------------------------ */
/* Body analysis                                                       */
/* ------------------------------------------------------------------ */

export interface HologramSegment {
  /** Normalised 0..1 development level for the segment, drives silhouette shape. */
  key:
    | 'shoulders'
    | 'chest'
    | 'arms'
    | 'waist'
    | 'hips'
    | 'quads'
    | 'calves'
    | 'back';
  development: number;
  /** -1..1 left/right balance offset. */
  balance: number;
}

export interface HologramData {
  /** 1 predates the fat layer; 2 carries `bodyFatBand`, `adiposity`, `definition`. */
  version: 1 | 2;
  /** Overall build descriptor derived from the estimate. */
  shoulderToWaist: number;
  bodyFatNormalized: number;
  muscleNormalized: number;
  symmetryNormalized: number;
  heightCm: number;
  sex: Sex;
  segments: HologramSegment[];
  /** Deterministic seed so the same assessment always renders the same hologram. */
  seed: number;
  /** `[body, bodyDeep, bodyBright, fatLayer]`. The last is the green rim. */
  accentPalette: string[];
  /**
   * The 5-point body-fat band the figure is drawn at.
   *
   * The figure changes in 5% steps rather than continuously, so two
   * assessments a week apart do not produce a subtly different body the user
   * has to squint at. The precise percentage is still what they read.
   */
  bodyFatBand?: number;
  /** 0..1 thickness of the subcutaneous layer drawn around the figure. */
  adiposity?: number;
  /** 0..1 how much muscle detail shows through that layer. */
  definition?: number;
}

/**
 * Tape measurements, in centimetres.
 *
 * Waist and neck drive the body-fat reading (plus hips for women, which the
 * circumference formula requires). The limb pairs are optional and only power
 * the left/right balance score.
 */
export interface BodyMeasurements {
  waistCm?: number;
  neckCm?: number;
  hipCm?: number;
  leftArmCm?: number;
  rightArmCm?: number;
  leftThighCm?: number;
  rightThighCm?: number;
  /** Around the widest part of the shoulders. Optional; sharpens the figure. */
  shoulderCm?: number;
}

/**
 * How a body-fat figure was produced, so the app can say so plainly:
 * `navy` from tape measurements, `bmi` from height and weight alone, and
 * `vision` from a photo when an optional AI provider is configured.
 */
export type BodyFatMethod = 'navy' | 'bmi' | 'vision';

export interface BodyAnalysisResult {
  bodyFatPercent: number;
  estimatedMuscleMassKg: number;
  waistBodyRatio: number;
  /**
   * Left/right balance. Null when neither limb pair was measured — an
   * unmeasured body is not a symmetrical one.
   */
  symmetryPercent: number | null;
  /** How the body-fat figure was derived. */
  method: BodyFatMethod;
  /** 0..1 confidence in the reading. Never presented as a medical claim. */
  confidence: number;
  hologramData: HologramData;
  provider: string;
}

export interface BodyAssessment extends BodyAnalysisResult {
  id: string;
  userId: string;
  createdAt: string;
  weightKg: number;
  assessmentNumber: number;
  /** An optional progress photo. It is stored privately and never analysed. */
  sourcePhotoId: string | null;
  /** The tape readings this assessment was computed from. */
  measurements: BodyMeasurements;
}

export interface AssessmentAvailability {
  available: boolean;
  daysRemaining: number;
  nextAvailableAt: string | null;
  lastAssessmentAt: string | null;
}

/* ------------------------------------------------------------------ */
/* Programs & workouts                                                 */
/* ------------------------------------------------------------------ */

export interface PrescribedSet {
  id?: string;
  setNumber: number;
  prescribedWeight: number | null;
  prescribedRepsMin: number;
  prescribedRepsMax: number;
  restSeconds: number;
  isWarmup: boolean;
}

export interface ProgramExercise {
  id?: string;
  exerciseId: string;
  orderIndex: number;
  sets: number;
  warmupSets: number;
  repsMin: number;
  repsMax: number;
  startingWeight: number | null;
  restSeconds: number;
  prescribedSets: PrescribedSet[];
  /** Populated when the client asks for a hydrated program. */
  exercise?: Exercise;
}

export interface CardioPrescription {
  type: string;
  minutes: number;
  exerciseId: string;
}

export interface ProgramDay {
  id?: string;
  dayNumber: number;
  focus: string;
  durationMinutes: number;
  exercises: ProgramExercise[];
  cardio: CardioPrescription | null;
}

export interface WorkoutProgram {
  id?: string;
  userId?: string;
  version: number;
  splitName: string;
  trainingDays: TrainingDays;
  sessionDurationMinutes: SessionDuration;
  generatedAt?: string;
  isActive?: boolean;
  days: ProgramDay[];
  /** Planned weekly volume per muscle: direct + secondary = effective. */
  volumeSummary: VolumeSummary;
}

export interface VolumeEntry {
  directSets: number;
  secondarySets: number;
  effectiveSets: number;
}

export type VolumeSummary = Record<MuscleGroup, VolumeEntry>;

export interface CompletedSet {
  id?: string;
  setNumber: number;
  actualWeight: number | null;
  actualReps: number | null;
  prescribedWeight: number | null;
  prescribedRepsMin: number;
  prescribedRepsMax: number;
  isWarmup: boolean;
  completedAt: string;
}

export interface CompletedExercise {
  id?: string;
  exerciseId: string;
  orderIndex: number;
  sets: CompletedSet[];
}

export interface CompletedWorkout {
  id: string;
  userId: string;
  programDayId: string | null;
  dayNumber: number;
  focus: string;
  startedAt: string;
  completedAt: string;
  durationSeconds: number;
  totalSets: number;
  totalVolumeKg: number;
  cardioMinutes: number;
  exercises: CompletedExercise[];
  personalRecords: PersonalRecord[];
}

export interface PersonalRecord {
  id?: string;
  exerciseId: string;
  recordType: 'weight' | 'reps' | 'estimated_1rm' | 'volume';
  value: number;
  previousValue: number | null;
  achievedAt: string;
  exerciseName?: string;
}

export type ScheduleStatus = 'scheduled' | 'completed' | 'missed' | 'rescheduled';

export interface ScheduledWorkout {
  id: string;
  programDayId: string;
  dayNumber: number;
  focus: string;
  scheduledDate: string;
  status: ScheduleStatus;
  durationMinutes: number;
  completedWorkoutId: string | null;
}

/* ------------------------------------------------------------------ */
/* Progression                                                         */
/* ------------------------------------------------------------------ */

export interface ExercisePerformance {
  exerciseId: string;
  performedAt: string;
  sets: Array<{ weight: number | null; reps: number | null; isWarmup: boolean }>;
  prescribedWeight: number | null;
  prescribedSets: number;
  prescribedRepsMin: number;
  prescribedRepsMax: number;
}

export interface ProgressionDecision {
  exerciseId: string;
  nextWeight: number | null;
  nextSets: number;
  nextRepsMin: number;
  nextRepsMax: number;
  reason: string;
  action: 'increase_weight' | 'increase_sets' | 'hold' | 'reduce_weight' | 'increase_reps' | 'initial';
}

/* ------------------------------------------------------------------ */
/* Subscription                                                        */
/* ------------------------------------------------------------------ */

export type SubscriptionStatus =
  | 'none'
  | 'active'
  | 'expired'
  | 'cancelled'
  | 'pending'
  | 'failed'
  | 'restored';

export type BillingPlatform = 'apple' | 'google' | 'mock';

export type BillingPeriod = 'month' | 'year';

/** One membership the app sells. See SUBSCRIPTION_PLANS for the catalogue. */
export interface SubscriptionPlan {
  /** Store product id, identical in App Store Connect and Play Console. */
  productId: string;
  period: BillingPeriod;
  /** What the member is charged for one period, in USD. */
  priceUsd: number;
  /** Undiscounted price, struck through beside the real one. Null if no offer. */
  listPriceUsd: number | null;
  /** Marketing badge, e.g. "BEST DEAL". */
  badge: string | null;
  /** True while the discount is a limited-time offer. */
  limitedTime: boolean;
}

export interface Subscription {
  id: string;
  userId: string;
  status: SubscriptionStatus;
  platform: BillingPlatform;
  productId: string;
  priceUsd: number;
  currentPeriodStart: string | null;
  currentPeriodEnd: string | null;
  cancelAtPeriodEnd: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Entitlement {
  active: boolean;
  status: SubscriptionStatus;
  expiresAt: string | null;
  productId: string | null;
  platform: BillingPlatform | null;
  /** Server clock at evaluation time — clients must not compute this themselves. */
  evaluatedAt: string;
}

/* ------------------------------------------------------------------ */
/* Progress & goals                                                    */
/* ------------------------------------------------------------------ */

export interface TrendPoint {
  date: string;
  value: number;
}

export interface BodyTrends {
  weightKg: TrendPoint[];
  bodyFatPercent: TrendPoint[];
  muscleMassKg: TrendPoint[];
  waistBodyRatio: TrendPoint[];
  symmetryPercent: TrendPoint[];
}

export interface StrengthProgressEntry {
  exerciseId: string;
  exerciseName: string;
  points: TrendPoint[];
  bestWeight: number;
  bestEstimated1rm: number;
}

export interface TrainingStats {
  completionRatePercent: number;
  workoutsCompleted: number;
  workoutsScheduled: number;
  weeklyVolume: TrendPoint[];
  totalSets: number;
  currentStreakDays: number;
}

export interface GoalProgress {
  goalType: GoalType;
  label: string;
  startValue: number | null;
  currentValue: number | null;
  targetValue: number | null;
  unit: string;
  progressPercent: number;
  detail: string;
  exerciseName?: string;
}

export interface ProgressOverview {
  latestAssessment: BodyAssessment | null;
  trends: BodyTrends;
  strength: StrengthProgressEntry[];
  personalRecords: PersonalRecord[];
  training: TrainingStats;
  goals: GoalProgress[];
}

/* ------------------------------------------------------------------ */
/* Settings                                                            */
/* ------------------------------------------------------------------ */

export type ThemeMode = 'dark' | 'light' | 'system';

export interface AppSettings {
  themeMode: ThemeMode;
  reducedMotion: boolean;
  units: 'metric';
}

/* ------------------------------------------------------------------ */
/* API envelopes                                                       */
/* ------------------------------------------------------------------ */

export interface ApiErrorBody {
  error: {
    code: string;
    message: string;
  };
}

export interface AuthTokens {
  accessToken: string;
  userId: string;
  isGuest: boolean;
}

/* ------------------------------------------------------------------ */
/* Cardio                                                              */
/* ------------------------------------------------------------------ */

export interface CardioExercise {
  id: string;
  name: string;
  equipment: EquipmentId[];
  availability: Availability;
  /** Relative demand — the generator prefers lower impact for heavier users. */
  impact: 'low' | 'moderate' | 'high';
  instructions: string;
  setup: string[];
  execution: string[];
  commonMistakes: string[];
  illustration: string;
}
