import { EXERCISE_CHOICES_PER_MUSCLE, MAX_EXERCISES_PER_MUSCLE } from '../constants';
import { EXERCISE_BY_ID, exercisesForMuscle, isExerciseAvailable } from '../exercises';
import { MUSCLE_GROUP_IDS } from '../muscles';
import type { EquipmentId, Exercise, ExercisePreference, GoalType, MuscleGroup, TrainingLevel, TrainingLocation } from '../types';
import { errors } from '../errors';

export interface SelectionContext {
  location: TrainingLocation;
  equipment: EquipmentId[];
  level: TrainingLevel;
  goals: GoalType[];
}

export interface MuscleChoiceSet {
  muscleGroup: MuscleGroup;
  muscleName: string;
  choices: Exercise[];
  /** True when the user's equipment cannot fill all four slots. */
  limitedByEquipment: boolean;
}

/**
 * ExerciseSelectionService
 *
 * Owns two responsibilities:
 *  1. Offering the four exercise choices per muscle shown in preferences.
 *  2. Turning preferences (or a "Generate for me" request) into the exact
 *     exercise pool the program generator is allowed to draw from.
 *
 * The hard product rule enforced here: if a user picked exercises for a muscle,
 * the generator may use ONLY those. Nothing is silently substituted.
 */
export class ExerciseSelectionService {
  /** The four options offered per muscle in the preferences screen. */
  buildChoiceSets(context: SelectionContext): MuscleChoiceSet[] {
    return MUSCLE_GROUP_IDS.map((muscle) => {
      const available = exercisesForMuscle(muscle).filter((e) =>
        isExerciseAvailable(e, context.location, context.equipment),
      );
      const ranked = rankExercises(available, context);
      const choices = pickDiverse(ranked, EXERCISE_CHOICES_PER_MUSCLE);
      return {
        muscleGroup: muscle,
        muscleName: muscle,
        choices,
        limitedByEquipment: choices.length < EXERCISE_CHOICES_PER_MUSCLE,
      };
    });
  }

  /** "Generate for me" — the AI picks the exercises itself. */
  generatePreferences(context: SelectionContext): ExercisePreference[] {
    const choiceSets = this.buildChoiceSets(context);
    const perMuscle = context.level === 'beginner' ? 2 : MAX_EXERCISES_PER_MUSCLE;

    return choiceSets.map((set) => ({
      muscleGroup: set.muscleGroup,
      exerciseIds: set.choices.slice(0, Math.min(perMuscle, set.choices.length)).map((e) => e.id),
      autoGenerated: true,
    }));
  }

  /**
   * Validates a user's manual selection. Throws a user-safe error rather than
   * quietly trimming, so the client can show exactly what went wrong.
   */
  validatePreferences(preferences: ExercisePreference[], context: SelectionContext): ExercisePreference[] {
    const seenMuscles = new Set<MuscleGroup>();

    for (const preference of preferences) {
      if (!MUSCLE_GROUP_IDS.includes(preference.muscleGroup)) {
        throw errors.invalidInput(`Unknown muscle group: ${preference.muscleGroup}`);
      }
      if (seenMuscles.has(preference.muscleGroup)) {
        throw errors.invalidInput(`Duplicate selection for ${preference.muscleGroup}.`);
      }
      seenMuscles.add(preference.muscleGroup);

      if (preference.exerciseIds.length > MAX_EXERCISES_PER_MUSCLE) {
        throw errors.invalidInput(
          `You can choose up to ${MAX_EXERCISES_PER_MUSCLE} exercises per muscle.`,
        );
      }
      if (new Set(preference.exerciseIds).size !== preference.exerciseIds.length) {
        throw errors.invalidInput('The same exercise was selected twice.');
      }

      for (const exerciseId of preference.exerciseIds) {
        const exercise = EXERCISE_BY_ID[exerciseId];
        if (!exercise) {
          throw errors.invalidInput(`Unknown exercise: ${exerciseId}`);
        }
        if (exercise.primaryMuscle !== preference.muscleGroup) {
          throw errors.invalidInput(`${exercise.name} does not train ${preference.muscleGroup}.`);
        }
        if (!isExerciseAvailable(exercise, context.location, context.equipment)) {
          throw errors.invalidInput(
            `${exercise.name} needs equipment you have not selected.`,
          );
        }
      }
    }

    return preferences.map((p) => ({ ...p, autoGenerated: p.autoGenerated ?? false }));
  }

  /**
   * Resolves the pool the program generator may use for a muscle.
   *
   * - User selected exercises → exactly those, nothing added.
   * - User selected none for that muscle → the AI fills it from what's available.
   */
  resolvePool(
    muscle: MuscleGroup,
    preferences: ExercisePreference[],
    context: SelectionContext,
  ): { pool: Exercise[]; userChosen: boolean } {
    const preference = preferences.find((p) => p.muscleGroup === muscle);
    const userChosen = Boolean(preference && !preference.autoGenerated && preference.exerciseIds.length > 0);

    if (preference && preference.exerciseIds.length > 0) {
      const pool = preference.exerciseIds
        .map((id) => EXERCISE_BY_ID[id])
        .filter((e): e is Exercise => Boolean(e))
        // Equipment can change after preferences were saved; anything no longer
        // trainable is dropped rather than prescribed.
        .filter((e) => isExerciseAvailable(e, context.location, context.equipment));
      if (pool.length > 0) return { pool, userChosen };
    }

    const available = exercisesForMuscle(muscle).filter((e) =>
      isExerciseAvailable(e, context.location, context.equipment),
    );
    return { pool: pickDiverse(rankExercises(available, context), MAX_EXERCISES_PER_MUSCLE), userChosen: false };
  }
}

/**
 * Ranks exercises for a user. Compounds and staple movements come first,
 * difficulty is matched to training level, and goals shift the weighting
 * (strength favours barbell compounds, muscle gain favours a mix).
 */
export function rankExercises(exercises: Exercise[], context: SelectionContext): Exercise[] {
  const wantsStrength = context.goals.includes('strength');
  const wantsMuscle = context.goals.includes('muscle_gain') || context.goals.includes('recomposition');

  return [...exercises]
    .map((exercise) => ({ exercise, score: scoreExercise(exercise, context, wantsStrength, wantsMuscle) }))
    .sort((a, b) => b.score - a.score || a.exercise.name.localeCompare(b.exercise.name))
    .map((entry) => entry.exercise);
}

function scoreExercise(
  exercise: Exercise,
  context: SelectionContext,
  wantsStrength: boolean,
  wantsMuscle: boolean,
): number {
  let score = 0;

  if (exercise.isCompound) score += wantsStrength ? 35 : 22;
  else score += wantsMuscle ? 12 : 8;

  const levelRank: Record<TrainingLevel, number> = { beginner: 0, intermediate: 1, advanced: 2 };
  const userRank = levelRank[context.level];
  const exerciseRank = levelRank[exercise.difficulty];
  if (exerciseRank <= userRank) score += 14 - (userRank - exerciseRank) * 4;
  else score -= (exerciseRank - userRank) * 16;

  // Loadable exercises progress more cleanly than bodyweight-only ones.
  if (exercise.loadFactor !== undefined) score += 8;
  if (exercise.isTimed) score -= 6;
  if (exercise.isUnilateral) score -= 3;

  if (context.level === 'beginner' && exercise.equipment.includes('resistance_machines')) score += 6;
  if (wantsStrength && exercise.equipment.includes('barbell')) score += 8;

  return score;
}

/**
 * Picks `count` exercises that are not all the same movement pattern, so the
 * four options offered per muscle are genuinely different choices.
 */
export function pickDiverse(ranked: Exercise[], count: number): Exercise[] {
  const picked: Exercise[] = [];
  const usedPatterns = new Map<string, number>();

  for (const exercise of ranked) {
    if (picked.length >= count) break;
    const pattern = movementPattern(exercise);
    const used = usedPatterns.get(pattern) ?? 0;
    if (used >= 2) continue;
    usedPatterns.set(pattern, used + 1);
    picked.push(exercise);
  }

  // Backfill if diversity filtering left slots empty.
  for (const exercise of ranked) {
    if (picked.length >= count) break;
    if (!picked.includes(exercise)) picked.push(exercise);
  }

  return picked;
}

function movementPattern(exercise: Exercise): string {
  const primaryEquipment =
    exercise.equipment.find((e) =>
      ['barbell', 'dumbbells', 'cable_machine', 'resistance_machines', 'smith_machine', 'bodyweight'].includes(e),
    ) ?? 'other';
  return `${exercise.category}:${primaryEquipment}`;
}
