import type { Exercise } from '../types';
import { ex } from './builder';

export const AB_EXERCISES: Exercise[] = [
  ex({
    id: 'crunch',
    name: 'Crunch',
    primaryMuscle: 'abs',
    secondaryMuscles: ['hip_flexors'],
    equipment: ['bodyweight'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'core',
    instructions: 'Spinal flexion against bodyweight — the simplest direct ab exercise.',
    setup: ['Lie on the back with the knees bent, feet flat.', 'Place the hands lightly at the temples.', 'Set the lower back flat.'],
    execution: ['Curl the ribs toward the pelvis.', 'Pause at the top contraction.', 'Lower slowly without relaxing completely.'],
    commonMistakes: ['Pulling on the head with the hands', 'Using momentum to bounce off the floor', 'Holding the breath'],
    repRangeMin: 15,
    repRangeMax: 25,
    restSeconds: 45,
    illustration: 'crunch',
    isBodyweight: true,
  }),
  ex({
    id: 'cable_crunch',
    name: 'Cable Crunch',
    primaryMuscle: 'abs',
    secondaryMuscles: ['obliques'],
    equipment: ['cable_machine'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'core',
    instructions: 'Loaded spinal flexion — the most progressible direct ab exercise.',
    setup: ['Attach a rope to a high pulley and kneel below it.', 'Hold the rope beside the head.', 'Hinge slightly at the hips and keep them fixed.'],
    execution: ['Crunch the ribs down toward the thighs.', 'Hold the contraction briefly.', 'Return under control to a stretch.'],
    commonMistakes: ['Hinging at the hips instead of flexing the spine', 'Pulling with the arms', 'Letting the stack pull you upright fast'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 60,
    illustration: 'crunch',
    loadFactor: 0.3,
  }),
  ex({
    id: 'reverse_crunch',
    name: 'Reverse Crunch',
    primaryMuscle: 'abs',
    secondaryMuscles: ['hip_flexors'],
    equipment: ['bodyweight'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'core',
    instructions: 'Posterior pelvic tilt against gravity, biasing the lower abdominal region.',
    setup: ['Lie on the back with the arms at the sides.', 'Bring the knees over the hips.', 'Press the lower back into the floor.'],
    execution: ['Curl the pelvis up off the floor.', 'Keep the movement small and controlled.', 'Lower slowly without arching the back.'],
    commonMistakes: ['Swinging the legs for momentum', 'Letting the lower back arch', 'Pushing off with the hands'],
    repRangeMin: 12,
    repRangeMax: 20,
    restSeconds: 45,
    illustration: 'leg_raise',
    isBodyweight: true,
  }),
  ex({
    id: 'hanging_leg_raise',
    name: 'Hanging Leg Raise',
    primaryMuscle: 'abs',
    secondaryMuscles: ['hip_flexors', 'forearms'],
    equipment: ['pullup_bar', 'bodyweight'],
    availability: 'both',
    difficulty: 'advanced',
    isCompound: false,
    category: 'core',
    instructions: 'Straight-leg raise from a hang — a demanding trunk flexion exercise.',
    setup: ['Hang from a bar with the arms straight.', 'Engage the shoulders slightly.', 'Keep the legs together and straight.'],
    execution: ['Raise the legs to hip height or above.', 'Finish with a small posterior pelvic tilt.', 'Lower slowly without swinging.'],
    commonMistakes: ['Swinging between reps', 'Lifting with the hip flexors only', 'Dropping the legs fast'],
    repRangeMin: 8,
    repRangeMax: 15,
    restSeconds: 75,
    illustration: 'leg_raise',
    isBodyweight: true,
  }),
  ex({
    id: 'hanging_knee_raise',
    name: 'Hanging Knee Raise',
    primaryMuscle: 'abs',
    secondaryMuscles: ['hip_flexors', 'forearms'],
    equipment: ['pullup_bar', 'dip_station', 'bodyweight'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: false,
    category: 'core',
    instructions: 'Bent-knee version of the hanging leg raise, a step toward the full movement.',
    setup: ['Hang from a bar or support on a dip station.', 'Set the shoulders lightly engaged.', 'Keep the knees together.'],
    execution: ['Raise the knees toward the chest.', 'Curl the pelvis at the top.', 'Lower under control without swinging.'],
    commonMistakes: ['Swinging the body', 'Stopping at 90 degrees without the pelvic curl', 'Dropping the legs quickly'],
    repRangeMin: 10,
    repRangeMax: 20,
    restSeconds: 60,
    illustration: 'leg_raise',
    isBodyweight: true,
  }),
  ex({
    id: 'lying_leg_raise',
    name: 'Lying Leg Raise',
    primaryMuscle: 'abs',
    secondaryMuscles: ['hip_flexors'],
    equipment: ['bodyweight'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'core',
    instructions: 'Floor leg raise with strong lower-ab and anti-extension demand.',
    setup: ['Lie flat with the hands under the glutes.', 'Press the lower back into the floor.', 'Keep the legs straight.'],
    execution: ['Raise the legs to vertical.', 'Lower slowly toward the floor.', 'Stop before the lower back lifts.'],
    commonMistakes: ['Letting the lower back arch off the floor', 'Bouncing the legs off the floor', 'Bending the knees heavily'],
    repRangeMin: 12,
    repRangeMax: 20,
    restSeconds: 45,
    illustration: 'leg_raise',
    isBodyweight: true,
  }),
  ex({
    id: 'plank',
    name: 'Plank',
    primaryMuscle: 'abs',
    secondaryMuscles: ['obliques', 'shoulders', 'glutes'],
    equipment: ['bodyweight'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'core',
    instructions: 'Anti-extension isometric that trains the trunk to resist movement.',
    setup: ['Set the forearms under the shoulders.', 'Extend the legs to a straight body line.', 'Tuck the pelvis slightly.'],
    execution: ['Hold the position for the prescribed time.', 'Squeeze the glutes and brace the abs.', 'Breathe steadily throughout.'],
    commonMistakes: ['Hips sagging toward the floor', 'Hips piked high', 'Holding the breath'],
    repRangeMin: 30,
    repRangeMax: 60,
    restSeconds: 45,
    illustration: 'plank',
    isBodyweight: true,
    isTimed: true,
  }),
  ex({
    id: 'side_plank',
    name: 'Side Plank',
    primaryMuscle: 'abs',
    secondaryMuscles: ['obliques', 'glutes', 'shoulders'],
    equipment: ['bodyweight'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'core',
    instructions: 'Lateral isometric training the obliques and lateral hip.',
    setup: ['Lie on one side with the forearm under the shoulder.', 'Stack the feet or stagger them.', 'Lift the hips to a straight line.'],
    execution: ['Hold the position for the prescribed time.', 'Keep the hips high and square.', 'Breathe steadily.'],
    commonMistakes: ['Hips dropping', 'Rotating the torso toward the floor', 'Shoulder collapsing into the joint'],
    repRangeMin: 20,
    repRangeMax: 45,
    restSeconds: 40,
    illustration: 'plank',
    isBodyweight: true,
    isTimed: true,
    isUnilateral: true,
  }),
  ex({
    id: 'ab_wheel_rollout',
    name: 'Ab Wheel',
    primaryMuscle: 'abs',
    secondaryMuscles: ['obliques', 'back', 'shoulders'],
    equipment: ['ab_wheel'],
    availability: 'both',
    difficulty: 'advanced',
    isCompound: false,
    category: 'core',
    instructions: 'Dynamic anti-extension rollout — one of the hardest core exercises.',
    setup: ['Kneel with the wheel under the shoulders.', 'Tuck the pelvis and brace hard.', 'Set the arms straight.'],
    execution: ['Roll out as far as the brace holds.', 'Keep the lower back from arching.', 'Pull back using the abs, not the arms.'],
    commonMistakes: ['Letting the lower back arch at full extension', 'Rolling out beyond controllable range', 'Pulling with the hip flexors'],
    repRangeMin: 6,
    repRangeMax: 12,
    restSeconds: 75,
    illustration: 'ab_wheel',
    isBodyweight: true,
  }),
  ex({
    id: 'dead_bug',
    name: 'Dead Bug',
    primaryMuscle: 'abs',
    secondaryMuscles: ['hip_flexors'],
    equipment: ['bodyweight'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'core',
    instructions: 'Controlled anti-extension drill with contralateral limb movement.',
    setup: ['Lie on the back with the arms straight up and knees over the hips.', 'Press the lower back into the floor.', 'Brace the abs.'],
    execution: ['Lower the opposite arm and leg toward the floor.', 'Stop before the lower back lifts.', 'Return and alternate sides.'],
    commonMistakes: ['Lower back arching off the floor', 'Moving too fast', 'Holding the breath'],
    repRangeMin: 10,
    repRangeMax: 20,
    restSeconds: 45,
    illustration: 'crunch',
    isBodyweight: true,
  }),
  ex({
    id: 'bicycle_crunch',
    name: 'Bicycle Crunch',
    primaryMuscle: 'abs',
    secondaryMuscles: ['obliques', 'hip_flexors'],
    equipment: ['bodyweight'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'core',
    instructions: 'Alternating rotational crunch that combines flexion and rotation.',
    setup: ['Lie on the back with the hands lightly at the temples.', 'Bring the knees over the hips.', 'Lift the shoulder blades off the floor.'],
    execution: ['Rotate one elbow toward the opposite knee.', 'Extend the other leg straight.', 'Alternate under control.'],
    commonMistakes: ['Yanking the head with the hands', 'Racing through the reps', 'Letting the lower back arch'],
    repRangeMin: 16,
    repRangeMax: 30,
    restSeconds: 45,
    illustration: 'twist',
    isBodyweight: true,
  }),
  ex({
    id: 'mountain_climber',
    name: 'Mountain Climber',
    primaryMuscle: 'abs',
    secondaryMuscles: ['hip_flexors', 'shoulders'],
    equipment: ['bodyweight'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'core',
    instructions: 'Dynamic plank variation adding a conditioning element to core work.',
    setup: ['Start in a high plank with the hands under the shoulders.', 'Set a straight body line.', 'Brace the abs.'],
    execution: ['Drive one knee toward the chest.', 'Return it and alternate legs.', 'Keep the hips low and steady.'],
    commonMistakes: ['Hips bouncing up and down', 'Hands drifting forward', 'Losing the trunk brace'],
    repRangeMin: 20,
    repRangeMax: 40,
    restSeconds: 45,
    illustration: 'plank',
    isBodyweight: true,
  }),
  ex({
    id: 'russian_twist',
    name: 'Russian Twist',
    primaryMuscle: 'abs',
    secondaryMuscles: ['obliques'],
    equipment: ['bodyweight', 'medicine_ball', 'weight_plates'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'core',
    instructions: 'Seated rotation drill for the obliques.',
    setup: ['Sit with the knees bent and heels lightly on the floor.', 'Lean back to about 45 degrees.', 'Hold a weight at the chest if loading.'],
    execution: ['Rotate the torso to one side.', 'Return through centre and rotate to the other side.', 'Keep the chest tall throughout.'],
    commonMistakes: ['Moving only the arms instead of the torso', 'Rounding the back heavily', 'Rushing the reps'],
    repRangeMin: 16,
    repRangeMax: 30,
    restSeconds: 45,
    illustration: 'twist',
    loadFactor: 0.08,
  }),
  ex({
    id: 'hollow_hold',
    name: 'Hollow Hold',
    primaryMuscle: 'abs',
    secondaryMuscles: ['hip_flexors'],
    equipment: ['bodyweight'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: false,
    category: 'core',
    instructions: 'Isometric hollow position that builds a strong braced trunk.',
    setup: ['Lie on the back with the arms overhead.', 'Press the lower back flat into the floor.', 'Lift the shoulders and legs slightly.'],
    execution: ['Hold the hollow shape for the prescribed time.', 'Keep the lower back pressed down.', 'Breathe shallow but steady.'],
    commonMistakes: ['Lower back lifting off the floor', 'Holding the legs too low too early', 'Holding the breath'],
    repRangeMin: 20,
    repRangeMax: 45,
    restSeconds: 45,
    illustration: 'plank',
    isBodyweight: true,
    isTimed: true,
  }),
  ex({
    id: 'decline_sit_up',
    name: 'Decline Sit-Up',
    primaryMuscle: 'abs',
    secondaryMuscles: ['hip_flexors'],
    equipment: ['bench', 'bodyweight'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: false,
    category: 'core',
    instructions: 'Sit-up on a decline bench for a longer range and higher load on the abs.',
    setup: ['Lock the legs into the decline bench.', 'Cross the arms over the chest.', 'Start lying back.'],
    execution: ['Curl up by flexing the spine, not just hinging at the hips.', 'Come up to about 45 degrees.', 'Lower slowly under control.'],
    commonMistakes: ['Pulling on the neck', 'Using pure hip flexion', 'Dropping back quickly'],
    repRangeMin: 12,
    repRangeMax: 20,
    restSeconds: 60,
    illustration: 'crunch',
    isBodyweight: true,
  }),
];
