import type { Exercise } from '../types';
import { ex } from './builder';

export const BICEPS_EXERCISES: Exercise[] = [
  ex({
    id: 'backpack_curl',
    name: 'Backpack Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: ['bodyweight'],
    availability: 'home',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Curl a loaded backpack when no dumbbells or bands are available at home.',
    setup: ['Load a backpack with books, water bottles or similar.', 'Hold the top handle or the straps with both hands.', 'Stand tall with the elbows at the sides.'],
    execution: ['Curl the pack up to chest height.', 'Squeeze at the top.', 'Lower slowly to full extension.'],
    commonMistakes: ['Swinging the pack with the hips', 'Letting the elbows drift forward', 'Using a load so light the set never gets hard'],
    repRangeMin: 12,
    repRangeMax: 20,
    restSeconds: 60,
    illustration: 'curl',
    isBodyweight: true,
  }),
  ex({
    id: 'barbell_curl',
    name: 'Barbell Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: ['barbell', 'weight_plates'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Bilateral biceps curl that allows the heaviest loading of the elbow flexors.',
    setup: ['Hold the bar at shoulder width with the palms up.', 'Stand tall with the elbows at the sides.', 'Brace the abs and squeeze the glutes.'],
    execution: ['Curl the bar up by flexing the elbows.', 'Keep the upper arms still.', 'Lower slowly to full extension.'],
    commonMistakes: ['Swinging the torso to start the rep', 'Letting the elbows drift forward', 'Cutting the bottom of the range short'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 75,
    illustration: 'curl',
    loadFactor: 0.3,
  }),
  ex({
    id: 'ez_bar_curl',
    name: 'EZ-Bar Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: ['ez_bar', 'weight_plates'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Curl on an angled bar that is kinder to the wrists than a straight bar.',
    setup: ['Grip the inner angles of the EZ-bar.', 'Stand tall with the elbows pinned to the sides.', 'Let the bar hang at arms length.'],
    execution: ['Curl the bar to chest height.', 'Squeeze at the top without swinging.', 'Lower under control to a full stretch.'],
    commonMistakes: ['Leaning back at the top', 'Moving the elbows forward', 'Bouncing out of the bottom'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 75,
    illustration: 'curl',
    loadFactor: 0.28,
  }),
  ex({
    id: 'dumbbell_curl',
    name: 'Dumbbell Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbells'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Two-arm dumbbell curl with supination through the rep.',
    setup: ['Hold the dumbbells at the sides, palms facing in.', 'Stand tall with the elbows fixed.', 'Brace the trunk.'],
    execution: ['Curl both dumbbells while rotating the palms up.', 'Squeeze at the top.', 'Lower slowly to full extension.'],
    commonMistakes: ['Swinging the weights up', 'Not fully extending at the bottom', 'Shrugging at the top'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 60,
    illustration: 'curl',
    loadFactor: 0.15,
  }),
  ex({
    id: 'alternating_dumbbell_curl',
    name: 'Alternating Dumbbell Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbells'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Single-arm alternating curl allowing a little more focus per side.',
    setup: ['Stand with a dumbbell in each hand, palms in.', 'Keep the elbows at the sides.', 'Brace the abs.'],
    execution: ['Curl one arm up, supinating as you go.', 'Lower it fully before starting the other side.', 'Keep the torso still throughout.'],
    commonMistakes: ['Rocking side to side', 'Starting the next rep before the last is finished', 'Short range of motion'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 60,
    illustration: 'curl',
    loadFactor: 0.15,
    isUnilateral: true,
  }),
  ex({
    id: 'hammer_curl',
    name: 'Hammer Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbells'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Neutral-grip curl that loads the brachialis and brachioradialis.',
    setup: ['Hold the dumbbells with the palms facing in.', 'Stand tall with the elbows at the sides.', 'Brace the trunk.'],
    execution: ['Curl the dumbbells keeping the palms facing in throughout.', 'Squeeze at the top.', 'Lower slowly to full extension.'],
    commonMistakes: ['Rotating the wrists', 'Swinging the weights', 'Letting the elbows travel forward'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 60,
    illustration: 'hammer_curl',
    loadFactor: 0.16,
  }),
  ex({
    id: 'incline_dumbbell_curl',
    name: 'Incline Dumbbell Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbells', 'bench'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: false,
    category: 'isolation',
    instructions: 'Curl from a stretched shoulder position for a longer biceps range.',
    setup: ['Set the bench to about 60 degrees.', 'Sit back and let the arms hang behind the torso.', 'Keep the shoulders down.'],
    execution: ['Curl the dumbbells without moving the upper arms.', 'Supinate as you reach the top.', 'Lower slowly to a full stretch.'],
    commonMistakes: ['Swinging the arms forward at the start', 'Lifting the shoulders off the bench', 'Cutting the stretch short'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 60,
    illustration: 'curl',
    loadFactor: 0.12,
  }),
  ex({
    id: 'preacher_curl',
    name: 'Preacher Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: ['ez_bar', 'bench', 'weight_plates'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Supported curl that eliminates body English entirely.',
    setup: ['Set the seat so the armpits rest over the pad top.', 'Grip the bar with the palms up.', 'Keep the upper arms flat on the pad.'],
    execution: ['Curl the bar up to a strong contraction.', 'Lower slowly to nearly full extension.', 'Keep the shoulders down throughout.'],
    commonMistakes: ['Dropping the weight quickly at the bottom', 'Lifting the elbows off the pad', 'Fully locking out under heavy load'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 75,
    illustration: 'curl',
    loadFactor: 0.22,
  }),
  ex({
    id: 'cable_curl',
    name: 'Cable Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: ['cable_machine'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Curl with constant tension from the cable through the whole range.',
    setup: ['Attach a straight or EZ handle to the low pulley.', 'Stand a step back from the stack.', 'Pin the elbows at the sides.'],
    execution: ['Curl the handle up to chest height.', 'Hold the peak contraction briefly.', 'Lower slowly, resisting the cable.'],
    commonMistakes: ['Leaning back as the weight rises', 'Letting the elbows drift', 'Allowing the stack to slam down'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 60,
    illustration: 'curl',
    loadFactor: 0.28,
  }),
  ex({
    id: 'concentration_curl',
    name: 'Concentration Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbells', 'bench'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Seated single-arm curl with the elbow braced against the inner thigh.',
    setup: ['Sit on a bench with the feet wide.', 'Brace the working elbow against the inner thigh.', 'Let the dumbbell hang at full extension.'],
    execution: ['Curl the dumbbell toward the shoulder.', 'Squeeze hard at the top.', 'Lower slowly to a full stretch.'],
    commonMistakes: ['Using the leg to push the arm up', 'Rounding the back heavily', 'Going too heavy and losing the brace'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 60,
    illustration: 'curl',
    loadFactor: 0.12,
    isUnilateral: true,
  }),
  ex({
    id: 'reverse_curl',
    name: 'Reverse Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: ['ez_bar', 'barbell', 'dumbbells'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Pronated curl that hits the brachioradialis and forearm extensors hard.',
    setup: ['Grip the bar with the palms facing down.', 'Stand tall with the elbows at the sides.', 'Keep the wrists straight.'],
    execution: ['Curl the bar up while keeping the palms down.', 'Pause at the top.', 'Lower slowly to full extension.'],
    commonMistakes: ['Letting the wrists collapse', 'Swinging the bar up', 'Loading too heavy for the grip'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 60,
    illustration: 'curl',
    loadFactor: 0.18,
  }),
  ex({
    id: 'band_curl',
    name: 'Band Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: ['resistance_bands'],
    availability: 'home',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Band curl for home sessions, with tension peaking at the top.',
    setup: ['Stand on the middle of the band.', 'Hold a handle in each hand, palms up.', 'Keep the elbows at the sides.'],
    execution: ['Curl the handles to shoulder height.', 'Squeeze at the top against maximum band tension.', 'Lower slowly to full extension.'],
    commonMistakes: ['Letting the band snap the arms down', 'Standing on too little band and losing tension', 'Swinging the torso'],
    repRangeMin: 15,
    repRangeMax: 25,
    restSeconds: 50,
    illustration: 'curl',
    isBodyweight: true,
  }),
];

export const TRICEPS_EXERCISES: Exercise[] = [
  ex({
    id: 'triceps_pushdown',
    name: 'Triceps Pushdown',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: ['cable_machine'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Straight-bar cable pushdown — the staple triceps isolation.',
    setup: ['Set the pulley high and attach a straight bar.', 'Stand close with a slight forward lean.', 'Pin the elbows to the sides.'],
    execution: ['Push the bar down to full elbow extension.', 'Squeeze the triceps at the bottom.', 'Let the bar rise to about 90 degrees under control.'],
    commonMistakes: ['Letting the elbows drift forward', 'Using bodyweight to drive the bar down', 'Shortening the range at the top'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 60,
    illustration: 'pushdown',
    loadFactor: 0.35,
  }),
  ex({
    id: 'rope_pushdown',
    name: 'Rope Pushdown',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: ['cable_machine'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Rope pushdown allowing the hands to separate for a stronger lockout contraction.',
    setup: ['Attach a rope to a high pulley.', 'Stand tall with the elbows at the sides.', 'Take a neutral grip on the rope.'],
    execution: ['Push down and spread the rope ends apart at the bottom.', 'Hold the contraction briefly.', 'Return under control to 90 degrees.'],
    commonMistakes: ['Flaring the elbows out', 'Leaning over the rope', 'Rushing the eccentric'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 60,
    illustration: 'pushdown',
    loadFactor: 0.3,
  }),
  ex({
    id: 'overhead_cable_extension',
    name: 'Overhead Cable Extension',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: ['cable_machine'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Overhead cable extension that loads the long head in a stretched position.',
    setup: ['Set the pulley low to mid and attach a rope.', 'Face away and bring the rope overhead.', 'Take a split stance with a braced trunk.'],
    execution: ['Extend the elbows until the arms are straight.', 'Keep the upper arms beside the ears.', 'Return to a deep stretch under control.'],
    commonMistakes: ['Letting the elbows flare wide', 'Arching the lower back', 'Moving the upper arms through the rep'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 60,
    illustration: 'overhead_extension',
    loadFactor: 0.25,
  }),
  ex({
    id: 'dumbbell_overhead_extension',
    name: 'Dumbbell Overhead Extension',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: ['dumbbells'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Two-hand overhead dumbbell extension for the triceps long head.',
    setup: ['Hold one dumbbell with both hands overhead.', 'Sit or stand tall with the ribs down.', 'Keep the upper arms vertical.'],
    execution: ['Lower the dumbbell behind the head by bending the elbows.', 'Stop at a comfortable stretch.', 'Extend back to lockout.'],
    commonMistakes: ['Flaring the elbows wide', 'Arching the lower back', 'Dropping into the stretch too fast'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 60,
    illustration: 'overhead_extension',
    loadFactor: 0.2,
  }),
  ex({
    id: 'skull_crusher',
    name: 'Skull Crusher',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: ['ez_bar', 'bench', 'weight_plates'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: false,
    category: 'isolation',
    instructions: 'Lying elbow extension, one of the most effective mass builders for the triceps.',
    setup: ['Lie flat holding an EZ-bar over the chest.', 'Set the upper arms slightly back from vertical.', 'Grip at the inner angles.'],
    execution: ['Lower the bar toward the forehead or just behind it.', 'Keep the upper arms still.', 'Extend back to the start.'],
    commonMistakes: ['Turning it into a press', 'Letting the elbows flare', 'Bouncing at the bottom'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 90,
    illustration: 'skullcrusher',
    loadFactor: 0.25,
  }),
  ex({
    id: 'close_grip_bench_press',
    name: 'Close-Grip Bench Press',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['chest', 'front_delts'],
    equipment: ['barbell', 'bench', 'weight_plates'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'push',
    instructions: 'Bench press with a shoulder-width grip that shifts the load to the triceps.',
    setup: ['Grip the bar at shoulder width.', 'Set the shoulder blades and plant the feet.', 'Unrack over the shoulders.'],
    execution: ['Lower to the lower chest with the elbows tucked.', 'Keep the wrists stacked over the elbows.', 'Press to full lockout.'],
    commonMistakes: ['Gripping far too narrow and straining the wrists', 'Flaring the elbows', 'Bouncing off the chest'],
    repRangeMin: 6,
    repRangeMax: 10,
    restSeconds: 120,
    illustration: 'barbell_press',
    loadFactor: 0.6,
  }),
  ex({
    id: 'triceps_dip',
    name: 'Dips',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['chest', 'front_delts'],
    equipment: ['dip_station', 'bodyweight'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'push',
    instructions: 'Upright dip with the elbows tucked, biasing the triceps.',
    setup: ['Mount the bars with the arms locked out.', 'Keep the torso as upright as possible.', 'Tuck the elbows close to the body.'],
    execution: ['Lower until the upper arms are near parallel.', 'Keep the elbows pointing back, not out.', 'Press back to full lockout.'],
    commonMistakes: ['Leaning forward, shifting work to the chest', 'Dropping too deep too soon', 'Flaring the elbows'],
    repRangeMin: 6,
    repRangeMax: 12,
    restSeconds: 120,
    illustration: 'dip',
    isBodyweight: true,
  }),
  ex({
    id: 'bench_dip',
    name: 'Bench Dip',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['front_delts'],
    equipment: ['bench', 'bodyweight'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: true,
    category: 'push',
    instructions: 'Dip performed with the hands on a bench behind you, easy to scale at home.',
    setup: ['Place the hands on a bench edge behind the hips.', 'Extend the legs out, heels on the floor.', 'Keep the chest tall.'],
    execution: ['Lower the hips until the upper arms are near parallel.', 'Keep the elbows tracking back.', 'Press back up to lockout.'],
    commonMistakes: ['Letting the hips drift away from the bench', 'Going deeper than the shoulders tolerate', 'Shrugging the shoulders up'],
    repRangeMin: 10,
    repRangeMax: 20,
    restSeconds: 75,
    illustration: 'dip',
    isBodyweight: true,
  }),
  ex({
    id: 'triceps_kickback',
    name: 'Kickback',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: ['dumbbells'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Triceps isolation with peak tension at full lockout.',
    setup: ['Hinge forward to roughly 45 degrees.', 'Pin the upper arm alongside the torso.', 'Start with the elbow bent to 90 degrees.'],
    execution: ['Extend the elbow until the arm is straight.', 'Squeeze the triceps at lockout.', 'Return under control without dropping the upper arm.'],
    commonMistakes: ['Swinging the dumbbell back', 'Letting the upper arm fall', 'Using weight that is far too heavy'],
    repRangeMin: 12,
    repRangeMax: 18,
    restSeconds: 50,
    illustration: 'pushdown',
    loadFactor: 0.08,
    isUnilateral: true,
  }),
  ex({
    id: 'machine_triceps_extension',
    name: 'Machine Triceps Extension',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: ['resistance_machines'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Fixed-path triceps extension, straightforward to progress week to week.',
    setup: ['Set the seat so the elbows align with the pivot.', 'Place the upper arms on the pad.', 'Grip the handles.'],
    execution: ['Extend the elbows to lockout.', 'Hold briefly at the bottom.', 'Return under control to a stretch.'],
    commonMistakes: ['Elbows not aligned with the machine pivot', 'Using the torso to push', 'Letting the stack slam'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 60,
    illustration: 'pushdown',
    loadFactor: 0.3,
  }),
  ex({
    id: 'diamond_push_up',
    name: 'Diamond Push-ups',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['chest', 'front_delts'],
    equipment: ['bodyweight'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'push',
    instructions: 'Narrow-hand push-up that shifts most of the load to the triceps.',
    setup: ['Place the hands together under the chest forming a diamond.', 'Set a straight body line.', 'Brace the abs and glutes.'],
    execution: ['Lower the chest to the hands.', 'Keep the elbows close to the ribs.', 'Press back to full extension.'],
    commonMistakes: ['Flaring the elbows wide', 'Hips sagging', 'Hands positioned too far forward'],
    repRangeMin: 8,
    repRangeMax: 15,
    restSeconds: 75,
    illustration: 'pushup',
    isBodyweight: true,
  }),
  ex({
    id: 'band_pushdown',
    name: 'Band Pushdown',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: ['resistance_bands'],
    availability: 'home',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Band triceps pushdown for home sessions with no cable stack.',
    setup: ['Anchor the band above head height.', 'Stand tall with the elbows at the sides.', 'Take the handles with light tension.'],
    execution: ['Push down to full elbow extension.', 'Squeeze at the bottom.', 'Return slowly against the band.'],
    commonMistakes: ['Letting the elbows travel forward', 'Leaning into the band', 'Letting the band recoil fast'],
    repRangeMin: 15,
    repRangeMax: 25,
    restSeconds: 50,
    illustration: 'pushdown',
    isBodyweight: true,
  }),
];

export const FOREARM_EXERCISES: Exercise[] = [
  ex({
    id: 'wrist_curl',
    name: 'Wrist Curl',
    primaryMuscle: 'forearms',
    secondaryMuscles: [],
    equipment: ['dumbbells', 'barbell', 'bench'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Direct work for the wrist flexors on the underside of the forearm.',
    setup: ['Rest the forearms on a bench or the thighs, palms up.', 'Let the wrists hang off the edge.', 'Hold the weight with a relaxed grip.'],
    execution: ['Let the weight roll to the fingertips.', 'Curl it back up by closing the hand and flexing the wrist.', 'Pause briefly at the top.'],
    commonMistakes: ['Moving the elbows', 'Using far too much weight', 'Skipping the stretch at the bottom'],
    repRangeMin: 12,
    repRangeMax: 20,
    restSeconds: 45,
    illustration: 'wrist_curl',
    loadFactor: 0.12,
  }),
  ex({
    id: 'reverse_wrist_curl',
    name: 'Reverse Wrist Curl',
    primaryMuscle: 'forearms',
    secondaryMuscles: [],
    equipment: ['dumbbells', 'barbell', 'bench'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Wrist extensor work that balances heavy gripping and curling.',
    setup: ['Rest the forearms on a bench, palms down.', 'Let the wrists hang off the edge.', 'Hold the weight with a firm grip.'],
    execution: ['Extend the wrists upward.', 'Hold the top briefly.', 'Lower slowly to a full stretch.'],
    commonMistakes: ['Lifting the forearms off the bench', 'Loading too heavy for the extensors', 'Rushing the reps'],
    repRangeMin: 12,
    repRangeMax: 20,
    restSeconds: 45,
    illustration: 'wrist_curl',
    loadFactor: 0.07,
  }),
  ex({
    id: 'farmer_carry',
    name: 'Farmer Carry',
    primaryMuscle: 'forearms',
    secondaryMuscles: ['traps', 'abs', 'obliques'],
    equipment: ['dumbbells', 'kettlebell'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: true,
    category: 'carry',
    instructions: 'Loaded carry that builds grip, trunk stability and upper-back endurance.',
    setup: ['Set two heavy dumbbells at the sides.', 'Hinge, grip hard and stand tall.', 'Set the shoulders down and back.'],
    execution: ['Walk with controlled steps and a tall posture.', 'Keep the weights from swinging.', 'Set the weights down under control at the end.'],
    commonMistakes: ['Leaning to one side', 'Shrugging the shoulders up', 'Dropping the weights from height'],
    repRangeMin: 30,
    repRangeMax: 60,
    restSeconds: 90,
    illustration: 'carry',
    loadFactor: 0.35,
    isTimed: true,
  }),
  ex({
    id: 'plate_pinch',
    name: 'Plate Pinch',
    primaryMuscle: 'forearms',
    secondaryMuscles: [],
    equipment: ['weight_plates'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'carry',
    instructions: 'Pinch grip hold that trains the thumb and finger flexors.',
    setup: ['Stand two plates together, smooth sides out.', 'Pinch them with the fingers and thumb.', 'Stand tall with the arms at the sides.'],
    execution: ['Hold the pinch for the prescribed time.', 'Keep the shoulders down and the arms straight.', 'Set the plates down before the grip fully fails.'],
    commonMistakes: ['Resting the plates on the thigh', 'Using plates with textured faces', 'Holding to complete failure repeatedly'],
    repRangeMin: 20,
    repRangeMax: 45,
    restSeconds: 60,
    illustration: 'carry',
    loadFactor: 0.12,
    isTimed: true,
  }),
  ex({
    id: 'grip_hold',
    name: 'Grip Hold',
    primaryMuscle: 'forearms',
    secondaryMuscles: ['traps'],
    equipment: ['barbell', 'dumbbells', 'weight_plates'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'carry',
    instructions: 'Static hold at the top of a deadlift position to build crushing grip.',
    setup: ['Load a bar or take heavy dumbbells.', 'Stand tall with the weight at arms length.', 'Set the shoulders down.'],
    execution: ['Hold the weight for the prescribed time.', 'Keep the trunk braced and the arms straight.', 'Lower under control.'],
    commonMistakes: ['Letting the shoulders round forward', 'Holding the breath the entire time', 'Dropping the bar from height'],
    repRangeMin: 20,
    repRangeMax: 45,
    restSeconds: 60,
    illustration: 'carry',
    loadFactor: 0.6,
    isTimed: true,
  }),
  ex({
    id: 'dead_hang',
    name: 'Dead Hang',
    primaryMuscle: 'forearms',
    secondaryMuscles: ['back', 'lats'],
    equipment: ['pullup_bar', 'bodyweight'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'carry',
    instructions: 'Passive bar hang for grip endurance and shoulder decompression.',
    setup: ['Grip the bar at shoulder width.', 'Hang with the arms straight.', 'Keep light tension through the shoulders.'],
    execution: ['Hold the hang for the prescribed time.', 'Breathe steadily.', 'Step down under control.'],
    commonMistakes: ['Hanging completely limp through the shoulders', 'Swinging', 'Dropping from the bar'],
    repRangeMin: 20,
    repRangeMax: 60,
    restSeconds: 60,
    illustration: 'pullup',
    isBodyweight: true,
    isTimed: true,
  }),
  ex({
    id: 'behind_back_wrist_curl',
    name: 'Behind-the-Back Wrist Curl',
    primaryMuscle: 'forearms',
    secondaryMuscles: [],
    equipment: ['barbell', 'weight_plates'],
    availability: 'gym',
    difficulty: 'intermediate',
    isCompound: false,
    category: 'isolation',
    instructions: 'Standing wrist curl with the bar behind the body for a strong stretch.',
    setup: ['Hold a bar behind the hips with the palms back.', 'Stand tall with the arms straight.', 'Relax the fingers slightly.'],
    execution: ['Let the bar roll down the fingers.', 'Curl it back up by flexing the wrists.', 'Pause at the top.'],
    commonMistakes: ['Bending the elbows', 'Using too much weight', 'Rushing the reps'],
    repRangeMin: 12,
    repRangeMax: 20,
    restSeconds: 45,
    illustration: 'wrist_curl',
    loadFactor: 0.2,
  }),
  ex({
    id: 'wrist_roller',
    name: 'Wrist Roller',
    primaryMuscle: 'forearms',
    secondaryMuscles: ['front_delts'],
    equipment: ['weight_plates'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Rolling a weight up and down a handle, training flexors and extensors together.',
    setup: ['Hold the roller at shoulder height with the arms extended.', 'Let the weight hang at the bottom of the cord.', 'Stand tall.'],
    execution: ['Roll the cord up by alternating wrist flexion.', 'Roll it back down under control.', 'Keep the arms extended throughout.'],
    commonMistakes: ['Letting the arms drop as they fatigue', 'Dropping the weight on the way down', 'Using a load that stops the reps immediately'],
    repRangeMin: 2,
    repRangeMax: 4,
    restSeconds: 75,
    illustration: 'wrist_curl',
    loadFactor: 0.05,
  }),
];
