import type { Exercise } from '../types';
import { ex } from './builder';

export const BACK_EXERCISES: Exercise[] = [
  ex({
    id: 'pull_up',
    name: 'Pull-ups',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'forearms', 'rear_delts'],
    equipment: ['pullup_bar', 'bodyweight'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'pull',
    instructions: 'Vertical pull with a pronated grip — the benchmark lat builder.',
    setup: ['Grip the bar slightly wider than shoulder width, palms forward.', 'Hang with the shoulder blades lightly engaged.', 'Brace the trunk and cross the ankles.'],
    execution: ['Pull the elbows down and back until the chin clears the bar.', 'Keep the chest tall and avoid swinging.', 'Lower under control to a full hang.'],
    commonMistakes: ['Kipping when strict reps are prescribed', 'Stopping short of a full hang', 'Shrugging instead of depressing the shoulder blades'],
    repRangeMin: 5,
    repRangeMax: 12,
    restSeconds: 150,
    illustration: 'pullup',
    isBodyweight: true,
  }),
  ex({
    id: 'chin_up',
    name: 'Chin-ups',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: ['pullup_bar', 'bodyweight'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'pull',
    instructions: 'Supinated vertical pull with a greater biceps contribution than pull-ups.',
    setup: ['Grip the bar shoulder width with the palms facing you.', 'Start from a full hang.', 'Brace the abs to stop the legs swinging.'],
    execution: ['Drive the elbows down to the ribs.', 'Pull until the chin passes the bar.', 'Control the descent to a full hang.'],
    commonMistakes: ['Using leg drive to start each rep', 'Half reps at the bottom', 'Letting the elbows flare forward'],
    repRangeMin: 5,
    repRangeMax: 12,
    restSeconds: 150,
    illustration: 'pullup',
    isBodyweight: true,
  }),
  ex({
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'rear_delts'],
    equipment: ['cable_machine'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: true,
    category: 'pull',
    instructions: 'Scalable vertical pull for lat width.',
    setup: ['Set the thigh pad so the legs are locked in.', 'Grip the bar wider than shoulder width.', 'Sit tall with a slight backward lean.'],
    execution: ['Pull the bar to the upper chest, leading with the elbows.', 'Squeeze the lats at the bottom.', 'Let the bar rise until the shoulders are fully stretched.'],
    commonMistakes: ['Leaning back excessively', 'Pulling behind the neck', 'Yanking with the arms instead of the back'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 105,
    illustration: 'pulldown',
    loadFactor: 0.6,
  }),
  ex({
    id: 'close_grip_pulldown',
    name: 'Close-Grip Pulldown',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'lats'],
    equipment: ['cable_machine'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: true,
    category: 'pull',
    instructions: 'Neutral close-grip pulldown emphasising lat thickness through a long range.',
    setup: ['Attach a close neutral-grip handle.', 'Lock the thighs under the pad.', 'Sit tall with the chest lifted.'],
    execution: ['Pull the handle to the sternum.', 'Keep the elbows tracking close to the ribs.', 'Return to a full stretch without shrugging.'],
    commonMistakes: ['Rocking the torso to move the weight', 'Cutting the stretch short', 'Curling the wrists'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 105,
    illustration: 'pulldown',
    loadFactor: 0.55,
  }),
  ex({
    id: 'barbell_row',
    name: 'Barbell Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'rear_delts', 'lower_back', 'forearms'],
    equipment: ['barbell', 'weight_plates'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'pull',
    instructions: 'Bent-over horizontal pull that loads the whole posterior chain.',
    setup: ['Hinge to roughly 45 degrees with a neutral spine.', 'Grip just outside the knees.', 'Brace the abs and set the lats.'],
    execution: ['Row the bar to the lower ribs.', 'Keep the torso angle fixed.', 'Lower under control to full arm extension.'],
    commonMistakes: ['Standing up as the bar rises', 'Rounding the lower back', 'Jerking the weight with the hips'],
    repRangeMin: 6,
    repRangeMax: 10,
    restSeconds: 150,
    illustration: 'row_barbell',
    loadFactor: 0.55,
  }),
  ex({
    id: 'pendlay_row',
    name: 'Pendlay Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['rear_delts', 'biceps', 'lower_back'],
    equipment: ['barbell', 'weight_plates'],
    availability: 'both',
    difficulty: 'advanced',
    isCompound: true,
    category: 'pull',
    instructions: 'Strict row from a dead stop on the floor with the torso parallel.',
    setup: ['Set the torso parallel to the floor.', 'Grip the bar just outside the knees.', 'Brace hard before each rep.'],
    execution: ['Pull explosively to the lower chest.', 'Return the bar fully to the floor.', 'Reset the brace before the next rep.'],
    commonMistakes: ['Letting the torso rise', 'Bouncing the bar off the floor', 'Rounding the upper back'],
    repRangeMin: 5,
    repRangeMax: 8,
    restSeconds: 150,
    illustration: 'row_barbell',
    loadFactor: 0.5,
  }),
  ex({
    id: 'dumbbell_row',
    name: 'Dumbbell Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'rear_delts', 'forearms'],
    equipment: ['dumbbells', 'bench'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: true,
    category: 'pull',
    instructions: 'Single-arm supported row with a long range of motion.',
    setup: ['Place one knee and hand on a bench.', 'Let the working arm hang straight down.', 'Keep the back flat and hips square.'],
    execution: ['Row the dumbbell to the hip, elbow close to the body.', 'Squeeze the shoulder blade at the top.', 'Lower to a full stretch.'],
    commonMistakes: ['Twisting the torso to finish the rep', 'Rowing to the shoulder instead of the hip', 'Using pure arm pull'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 90,
    illustration: 'row_dumbbell',
    loadFactor: 0.3,
    isUnilateral: true,
  }),
  ex({
    id: 'chest_supported_row',
    name: 'Chest-Supported Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['rear_delts', 'biceps'],
    equipment: ['dumbbells', 'bench'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: true,
    category: 'pull',
    instructions: 'Row with the chest braced against an incline bench, removing lower-back fatigue.',
    setup: ['Set an incline bench to about 30-45 degrees.', 'Lie face down with the chest on the pad.', 'Let the dumbbells hang straight down.'],
    execution: ['Row the dumbbells toward the hips.', 'Pinch the shoulder blades at the top.', 'Lower slowly to a full stretch.'],
    commonMistakes: ['Lifting the chest off the pad', 'Using momentum from the legs', 'Shortening the range of motion'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 90,
    illustration: 'row_dumbbell',
    loadFactor: 0.25,
  }),
  ex({
    id: 'cable_row',
    name: 'Seated Cable Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'rear_delts', 'forearms'],
    equipment: ['cable_machine'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: true,
    category: 'pull',
    instructions: 'Seated horizontal pull with constant cable tension.',
    setup: ['Sit with a soft knee bend and the feet on the platform.', 'Grip the handle with a tall chest.', 'Set the torso near vertical.'],
    execution: ['Pull the handle to the lower ribs.', 'Drive the elbows straight back.', 'Let the arms extend fully at the front without collapsing the chest.'],
    commonMistakes: ['Swinging the torso back and forth', 'Shrugging at the finish', 'Rounding the back at the stretch'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 105,
    illustration: 'row_cable',
    loadFactor: 0.55,
  }),
  ex({
    id: 'machine_row',
    name: 'Machine Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'rear_delts'],
    equipment: ['resistance_machines'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: true,
    category: 'pull',
    instructions: 'Guided horizontal row, simple to progress and easy to train close to failure.',
    setup: ['Set the chest pad so the handles align with the mid torso.', 'Plant the feet and brace the trunk.', 'Grip the handles with a tall chest.'],
    execution: ['Row the handles back, leading with the elbows.', 'Hold the contraction briefly.', 'Return until the shoulder blades protract.'],
    commonMistakes: ['Seat set too high or low', 'Pulling with the arms only', 'Letting the stack slam'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 105,
    illustration: 'row_cable',
    loadFactor: 0.55,
  }),
  ex({
    id: 'inverted_row',
    name: 'Inverted Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'rear_delts', 'abs'],
    equipment: ['bodyweight', 'suspension_trainer'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: true,
    category: 'pull',
    instructions: 'Bodyweight horizontal pull — scalable by changing body angle.',
    setup: ['Set a bar or straps at hip to chest height.', 'Hang underneath with a straight body line.', 'Grip slightly wider than shoulders.'],
    execution: ['Pull the chest to the bar or handles.', 'Keep the hips in line with the shoulders.', 'Lower under control to full extension.'],
    commonMistakes: ['Letting the hips drop', 'Shrugging the shoulders', 'Shortening the pull'],
    repRangeMin: 8,
    repRangeMax: 15,
    restSeconds: 75,
    illustration: 'row_dumbbell',
    isBodyweight: true,
  }),
  ex({
    id: 'straight_arm_pulldown',
    name: 'Straight-Arm Pulldown',
    primaryMuscle: 'back',
    secondaryMuscles: ['triceps', 'abs'],
    equipment: ['cable_machine'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Lat isolation that trains shoulder extension without elbow flexion.',
    setup: ['Set the pulley high and grip a straight bar.', 'Step back and hinge slightly at the hips.', 'Keep a fixed soft elbow bend.'],
    execution: ['Drive the bar down to the thighs using the lats.', 'Squeeze at the bottom.', 'Let the arms rise until a lat stretch is felt.'],
    commonMistakes: ['Bending the elbows into a pushdown', 'Using bodyweight to drive the bar down', 'Standing too close to the stack'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 75,
    illustration: 'pulldown',
    loadFactor: 0.25,
  }),
  ex({
    id: 'deadlift',
    name: 'Deadlift',
    primaryMuscle: 'back',
    secondaryMuscles: ['hamstrings', 'glutes', 'lower_back', 'traps', 'forearms', 'quads'],
    equipment: ['barbell', 'weight_plates'],
    availability: 'both',
    difficulty: 'advanced',
    isCompound: true,
    category: 'hinge',
    instructions: 'Full-body pull from the floor — the heaviest posterior-chain lift in the library.',
    setup: ['Stand with the bar over mid-foot, feet hip width.', 'Hinge and grip just outside the knees.', 'Set the lats, flatten the back and take the slack out.'],
    execution: ['Push the floor away and keep the bar against the legs.', 'Extend the hips and knees together.', 'Lock out tall, then hinge the bar back down.'],
    commonMistakes: ['Letting the hips shoot up first', 'Rounding the lower back', 'Hyperextending at lockout'],
    repRangeMin: 3,
    repRangeMax: 6,
    restSeconds: 180,
    illustration: 'deadlift',
    loadFactor: 1.0,
  }),
  ex({
    id: 'rack_pull',
    name: 'Rack Pull',
    primaryMuscle: 'back',
    secondaryMuscles: ['traps', 'glutes', 'hamstrings', 'forearms'],
    equipment: ['barbell', 'squat_rack', 'weight_plates'],
    availability: 'gym',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'hinge',
    instructions: 'Partial deadlift from knee height that overloads the upper back and lockout.',
    setup: ['Set the pins at or just below knee height.', 'Grip the bar just outside the legs.', 'Set the lats and brace hard.'],
    execution: ['Drive the hips forward to lockout.', 'Keep the bar tight to the thighs.', 'Lower back to the pins under control.'],
    commonMistakes: ['Bouncing the bar off the pins', 'Leaning back at lockout', 'Letting the shoulders round forward'],
    repRangeMin: 5,
    repRangeMax: 8,
    restSeconds: 180,
    illustration: 'deadlift',
    loadFactor: 1.15,
  }),
  ex({
    id: 'band_row',
    name: 'Band Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'rear_delts'],
    equipment: ['resistance_bands'],
    availability: 'home',
    difficulty: 'beginner',
    isCompound: true,
    category: 'pull',
    instructions: 'Seated or standing band row for home training without weights.',
    setup: ['Anchor the band at chest height or loop it around the feet.', 'Sit or stand tall with light tension on the band.', 'Hold the handles with the arms extended.'],
    execution: ['Pull the handles to the lower ribs.', 'Squeeze the shoulder blades together.', 'Return slowly against the tension.'],
    commonMistakes: ['Leaning back to generate range', 'Letting the band pull the arms forward quickly', 'Shrugging'],
    repRangeMin: 12,
    repRangeMax: 20,
    restSeconds: 60,
    illustration: 'row_cable',
    isBodyweight: true,
  }),
  ex({
    id: 'single_arm_lat_pulldown',
    name: 'Single-Arm Lat Pulldown',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'obliques'],
    equipment: ['cable_machine'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: true,
    category: 'pull',
    instructions: 'Unilateral pulldown that exposes and corrects side-to-side differences.',
    setup: ['Attach a single handle to a high pulley.', 'Kneel or sit facing the stack.', 'Start with the arm fully extended overhead.'],
    execution: ['Pull the elbow down toward the ribs.', 'Allow a natural slight torso rotation.', 'Return to a full overhead stretch.'],
    commonMistakes: ['Twisting the whole torso to cheat', 'Pulling with the biceps only', 'Skipping the stretch'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 75,
    illustration: 'pulldown',
    loadFactor: 0.25,
    isUnilateral: true,
  }),
  ex({
    id: 'barbell_shrug',
    name: 'Barbell Shrug',
    primaryMuscle: 'back',
    secondaryMuscles: ['traps', 'forearms'],
    equipment: ['barbell', 'weight_plates'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Direct trap work through pure scapular elevation.',
    setup: ['Hold the bar at arms length in front of the thighs.', 'Stand tall with a braced trunk.', 'Let the shoulders relax down.'],
    execution: ['Shrug the shoulders straight up toward the ears.', 'Pause briefly at the top.', 'Lower slowly to a full stretch.'],
    commonMistakes: ['Rolling the shoulders', 'Bending the elbows', 'Using momentum from the knees'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 75,
    illustration: 'shrug',
    loadFactor: 0.6,
  }),
  ex({
    id: 'towel_door_row',
    name: 'Towel Door Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'rear_delts', 'forearms'],
    equipment: ['bodyweight'],
    availability: 'home',
    difficulty: 'beginner',
    isCompound: true,
    category: 'pull',
    instructions: 'Horizontal pull using a towel looped around a secured door handle — the practical no-equipment back exercise.',
    setup: ['Loop a strong towel around both handles of a closed, latched door.', 'Hold one end in each hand and lean back with the feet close to the door.', 'Set a straight body line from head to heels.'],
    execution: ['Pull the chest toward the door, elbows driving back.', 'Squeeze the shoulder blades together.', 'Lower under control to full arm extension.'],
    commonMistakes: ['Using a door that opens toward you', 'Letting the hips sag', 'Pulling with the arms instead of the back'],
    repRangeMin: 10,
    repRangeMax: 20,
    restSeconds: 75,
    illustration: 'row_dumbbell',
    isBodyweight: true,
  }),
  ex({
    id: 'back_extension',
    name: 'Back Extension',
    primaryMuscle: 'back',
    secondaryMuscles: ['glutes', 'hamstrings', 'lower_back'],
    equipment: ['resistance_machines', 'bodyweight'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'hinge',
    instructions: 'Hip extension against gravity, training the spinal erectors and glutes.',
    setup: ['Set the pad just below the hip crease.', 'Cross the arms over the chest.', 'Start with the torso hanging down.'],
    execution: ['Extend the hips until the body forms a straight line.', 'Squeeze the glutes at the top.', 'Lower under control.'],
    commonMistakes: ['Hyperextending past neutral', 'Using a jerky tempo', 'Pad set too high'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 75,
    illustration: 'good_morning',
    isBodyweight: true,
  }),
];
