import type { CardioExercise } from '../types';

export const CARDIO_EXERCISES: CardioExercise[] = [
  {
    id: 'cardio_walking',
    name: 'Walking',
    equipment: ['bodyweight'],
    availability: 'both',
    impact: 'low',
    instructions: 'Steady outdoor or indoor walking at a brisk, conversational pace.',
    setup: ['Choose a flat route or a clear space.', 'Wear supportive shoes.', 'Start at an easy pace for the first minute.'],
    execution: ['Walk briskly enough that speaking is possible but not easy.', 'Keep a tall posture and relaxed arms.', 'Ease off for the final minute.'],
    commonMistakes: ['Starting far too fast', 'Very short choppy strides', 'Skipping the easy first minute'],
    illustration: 'cardio_walk',
  },
  {
    id: 'cardio_incline_walk',
    name: 'Incline Walk',
    equipment: ['treadmill'],
    availability: 'both',
    impact: 'low',
    instructions: 'Treadmill walking at an incline — high calorie burn with very low joint stress.',
    setup: ['Set the incline between 6 and 12 percent.', 'Set a pace you can hold without gripping the rails.', 'Start flat for the first minute.'],
    execution: ['Walk tall without leaning on the handrails.', 'Keep the steps full length.', 'Lower the incline for the last minute.'],
    commonMistakes: ['Holding the rails, which removes most of the work', 'Setting the incline too high to walk normally', 'Very short strides'],
    illustration: 'cardio_walk',
  },
  {
    id: 'cardio_treadmill_run',
    name: 'Treadmill Run',
    equipment: ['treadmill'],
    availability: 'both',
    impact: 'high',
    instructions: 'Easy-to-moderate continuous running on a treadmill.',
    setup: ['Start with a one-minute walk.', 'Build to a pace you can sustain for the full duration.', 'Keep the incline at 1 percent.'],
    execution: ['Run with a relaxed upper body.', 'Land under the hips rather than far in front.', 'Finish with an easy walk.'],
    commonMistakes: ['Going out too hard', 'Heavy over-striding', 'Skipping the cool-down walk'],
    illustration: 'cardio_walk',
  },
  {
    id: 'cardio_cycling',
    name: 'Cycling',
    equipment: ['stationary_bike'],
    availability: 'both',
    impact: 'low',
    instructions: 'Steady stationary cycling at a moderate resistance.',
    setup: ['Set the saddle so the knee is slightly bent at the bottom.', 'Start at a light resistance.', 'Sit tall with relaxed shoulders.'],
    execution: ['Hold a cadence around 80-90 rpm.', 'Keep the resistance high enough to feel the legs working.', 'Spin easy for the last minute.'],
    commonMistakes: ['Saddle far too low', 'Almost no resistance, so the legs do nothing', 'Rocking the hips side to side'],
    illustration: 'cardio_bike',
  },
  {
    id: 'cardio_elliptical',
    name: 'Elliptical',
    equipment: ['elliptical'],
    availability: 'both',
    impact: 'low',
    instructions: 'Low-impact full-body cardio on an elliptical trainer.',
    setup: ['Step on and hold the moving handles.', 'Set a light resistance to begin.', 'Stand tall.'],
    execution: ['Drive with the legs and push and pull with the arms.', 'Keep a smooth, even stride.', 'Ease the resistance down at the end.'],
    commonMistakes: ['Leaning on the fixed handles', 'Resistance set too low', 'Bouncing rather than gliding'],
    illustration: 'cardio_elliptical',
  },
  {
    id: 'cardio_rowing',
    name: 'Rowing',
    equipment: ['rowing_machine'],
    availability: 'both',
    impact: 'low',
    instructions: 'Continuous rowing — a full-body, low-impact conditioning option.',
    setup: ['Strap the feet in securely.', 'Set the damper between 3 and 5.', 'Start at the catch with the shins vertical.'],
    execution: ['Drive with the legs, then swing the torso, then pull the arms.', 'Reverse that order on the recovery.', 'Keep a steady stroke rate around 24 per minute.'],
    commonMistakes: ['Pulling with the arms first', 'Rounding the lower back', 'Rushing the recovery'],
    illustration: 'cardio_row',
  },
  {
    id: 'cardio_jump_rope',
    name: 'Jump Rope',
    equipment: ['jump_rope'],
    availability: 'both',
    impact: 'high',
    instructions: 'Skipping intervals — very time efficient and needs almost no space.',
    setup: ['Size the rope so the handles reach the armpits when stood on.', 'Find a forgiving surface.', 'Start with slow single bounces.'],
    execution: ['Keep the jumps low, an inch off the floor.', 'Turn the rope with the wrists, not the arms.', 'Break into intervals if unbroken skipping is too hard.'],
    commonMistakes: ['Jumping far too high', 'Swinging from the shoulders', 'Landing with locked knees'],
    illustration: 'cardio_jump',
  },
  {
    id: 'cardio_stair_climber',
    name: 'Stair Climber',
    equipment: ['resistance_machines'],
    availability: 'gym',
    impact: 'moderate',
    instructions: 'Continuous stepping on a stair machine at a steady pace.',
    setup: ['Start at a slow speed for the first minute.', 'Stand tall without gripping the rails hard.', 'Set the full foot on each step.'],
    execution: ['Step at a pace you can maintain for the full duration.', 'Keep the torso upright.', 'Slow down for the final minute.'],
    commonMistakes: ['Leaning heavily on the handrails', 'Taking tiny partial steps', 'Setting a pace that cannot be held'],
    illustration: 'cardio_walk',
  },
];

export const CARDIO_BY_ID: Record<string, CardioExercise> = Object.fromEntries(
  CARDIO_EXERCISES.map((c) => [c.id, c]),
);
