import type { Exercise } from '../types';
import { ex } from './builder';

export const CHEST_EXERCISES: Exercise[] = [
  ex({
    id: 'bench_press',
    name: 'Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'front_delts'],
    equipment: ['barbell', 'bench', 'weight_plates'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'push',
    instructions: 'The primary horizontal press for building chest thickness and pressing strength.',
    setup: [
      'Lie flat with eyes directly under the bar and feet planted.',
      'Grip roughly 1.5x shoulder width and pull the shoulder blades down and back.',
      'Unrack to a position directly over the shoulder joint.',
    ],
    execution: [
      'Lower the bar under control to the lower chest, elbows around 45 degrees.',
      'Touch the chest lightly without bouncing.',
      'Press back to lockout, driving the feet into the floor.',
    ],
    commonMistakes: ['Flaring the elbows to 90 degrees', 'Bouncing the bar off the chest', 'Letting the hips leave the bench'],
    repRangeMin: 6,
    repRangeMax: 10,
    restSeconds: 150,
    illustration: 'barbell_press',
    loadFactor: 0.75,
  }),
  ex({
    id: 'incline_bench_press',
    name: 'Incline Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['front_delts', 'triceps'],
    equipment: ['barbell', 'bench', 'weight_plates'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'push',
    instructions: 'Barbell press on a 30-45 degree incline that biases the upper chest.',
    setup: ['Set the bench to roughly 30 degrees.', 'Grip slightly narrower than flat bench.', 'Retract the shoulder blades before unracking.'],
    execution: ['Lower to the upper chest just below the collarbone.', 'Keep the wrists stacked over the elbows.', 'Press up and slightly back over the shoulders.'],
    commonMistakes: ['Setting the bench too steep, turning it into a shoulder press', 'Letting the bar drift toward the throat', 'Shrugging at the top'],
    repRangeMin: 6,
    repRangeMax: 10,
    restSeconds: 150,
    illustration: 'incline_press',
    loadFactor: 0.6,
  }),
  ex({
    id: 'decline_bench_press',
    name: 'Decline Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps'],
    equipment: ['barbell', 'bench', 'weight_plates'],
    availability: 'gym',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'push',
    instructions: 'Decline press emphasising the lower chest fibres with a shorter range of motion.',
    setup: ['Secure the legs in the decline pads.', 'Take a grip slightly wider than shoulder width.', 'Have a spotter hand off when possible.'],
    execution: ['Lower to the lower chest with controlled tempo.', 'Keep the elbows tucked around 45 degrees.', 'Press to lockout without hyperextending.'],
    commonMistakes: ['Sitting up too fast after the set', 'Excessive arch', 'Using a grip that is far too wide'],
    repRangeMin: 6,
    repRangeMax: 10,
    restSeconds: 150,
    illustration: 'barbell_press',
    loadFactor: 0.8,
  }),
  ex({
    id: 'dumbbell_bench_press',
    name: 'Dumbbell Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'front_delts'],
    equipment: ['dumbbells', 'bench'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: true,
    category: 'push',
    instructions: 'Dumbbell horizontal press with a longer range of motion and per-side balance.',
    setup: ['Sit with the dumbbells on the thighs and kick them into position.', 'Plant the feet and set the shoulder blades.', 'Start with the dumbbells over the chest.'],
    execution: ['Lower until the upper arms are level with the torso.', 'Keep the dumbbells stacked over the elbows.', 'Press up and slightly together without clashing.'],
    commonMistakes: ['Dropping the elbows below a safe depth on the first session', 'Banging the dumbbells together', 'Losing the shoulder-blade set'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 120,
    illustration: 'dumbbell_press',
    loadFactor: 0.3,
  }),
  ex({
    id: 'incline_dumbbell_press',
    name: 'Incline Dumbbell Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['front_delts', 'triceps'],
    equipment: ['dumbbells', 'bench'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: true,
    category: 'push',
    instructions: 'Upper-chest focused dumbbell press performed on an incline bench.',
    setup: ['Set the bench near 30 degrees.', 'Kick the dumbbells up one at a time.', 'Keep the lower back in a natural arch.'],
    execution: ['Lower to the upper chest with the elbows under the wrists.', 'Pause briefly at the stretch.', 'Press back over the upper chest.'],
    commonMistakes: ['Flaring the elbows wide', 'Pressing the dumbbells too far behind the head', 'Bench angle above 45 degrees'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 120,
    illustration: 'incline_press',
    loadFactor: 0.26,
  }),
  ex({
    id: 'decline_dumbbell_press',
    name: 'Decline Dumbbell Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbells', 'bench'],
    availability: 'gym',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'push',
    instructions: 'Decline dumbbell press targeting the sternal and lower chest.',
    setup: ['Lock the legs into the decline bench.', 'Have the dumbbells passed to you if heavy.', 'Set the shoulder blades before the first rep.'],
    execution: ['Lower to the lower chest under control.', 'Keep a slight tuck in the elbows.', 'Press to a soft lockout.'],
    commonMistakes: ['Rushing to sit upright after the set', 'Over-tucking the elbows', 'Bouncing at the bottom'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 120,
    illustration: 'dumbbell_press',
    loadFactor: 0.3,
  }),
  ex({
    id: 'push_up',
    name: 'Push-ups',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'front_delts', 'abs'],
    equipment: ['bodyweight'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: true,
    category: 'push',
    instructions: 'Foundational bodyweight press that trains the chest, triceps and trunk together.',
    setup: ['Hands slightly wider than shoulders, under the chest.', 'Set a straight line from head to heels.', 'Brace the abs and squeeze the glutes.'],
    execution: ['Lower until the chest is a fist from the floor.', 'Keep the elbows around 45 degrees from the torso.', 'Press away and protract slightly at the top.'],
    commonMistakes: ['Sagging hips', 'Flaring elbows to 90 degrees', 'Cutting the range of motion short'],
    repRangeMin: 10,
    repRangeMax: 20,
    restSeconds: 75,
    illustration: 'pushup',
    isBodyweight: true,
  }),
  ex({
    id: 'weighted_push_up',
    name: 'Weighted Push-ups',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'front_delts', 'abs'],
    equipment: ['bodyweight', 'weight_plates'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'push',
    instructions: 'Push-ups loaded with a plate or pack once bodyweight reps exceed 20.',
    setup: ['Have a partner place the plate on the upper back, or wear a weighted pack.', 'Set the same hand position as a standard push-up.', 'Brace hard before the first rep.'],
    execution: ['Lower under control to a fist from the floor.', 'Keep the torso rigid — no hip sag.', 'Press away without shifting the load.'],
    commonMistakes: ['Load placed too low on the back', 'Losing the brace mid set', 'Partial range of motion'],
    repRangeMin: 6,
    repRangeMax: 12,
    restSeconds: 90,
    illustration: 'pushup',
    loadFactor: 0.15,
  }),
  ex({
    id: 'incline_push_up',
    name: 'Incline Push-ups',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'front_delts'],
    equipment: ['bodyweight', 'bench'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: true,
    category: 'push',
    instructions: 'Push-up regression with the hands elevated, ideal for building the first full reps.',
    setup: ['Place the hands on a bench, chair or step.', 'Walk the feet back to a straight body line.', 'Brace the trunk.'],
    execution: ['Lower the chest to the edge of the surface.', 'Keep the elbows moderately tucked.', 'Press back to full extension.'],
    commonMistakes: ['Hips leading the movement', 'Hands too wide', 'Using an unstable surface'],
    repRangeMin: 10,
    repRangeMax: 20,
    restSeconds: 60,
    illustration: 'pushup',
    isBodyweight: true,
  }),
  ex({
    id: 'dumbbell_fly',
    name: 'Dumbbell Fly',
    primaryMuscle: 'chest',
    secondaryMuscles: ['front_delts'],
    equipment: ['dumbbells', 'bench'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Single-joint chest isolation loading the stretched position.',
    setup: ['Lie flat with the dumbbells pressed over the chest.', 'Set a soft, fixed elbow bend.', 'Pull the shoulder blades back and down.'],
    execution: ['Open the arms in a wide arc until a stretch is felt.', 'Stop level with the torso.', 'Squeeze the chest to bring the dumbbells back together.'],
    commonMistakes: ['Turning it into a press by bending the elbows', 'Going far below shoulder level', 'Using weight that forces momentum'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 75,
    illustration: 'fly',
    loadFactor: 0.12,
  }),
  ex({
    id: 'incline_dumbbell_fly',
    name: 'Incline Dumbbell Fly',
    primaryMuscle: 'chest',
    secondaryMuscles: ['front_delts'],
    equipment: ['dumbbells', 'bench'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: false,
    category: 'isolation',
    instructions: 'Fly variation on an incline that biases the upper chest.',
    setup: ['Set the bench to 30 degrees.', 'Start with the dumbbells over the upper chest.', 'Fix a slight elbow bend.'],
    execution: ['Lower in a wide arc to a comfortable stretch.', 'Keep the wrists neutral.', 'Return along the same arc, squeezing at the top.'],
    commonMistakes: ['Excessive range at the bottom', 'Elbow angle changing through the rep', 'Shrugging the shoulders'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 75,
    illustration: 'fly',
    loadFactor: 0.1,
  }),
  ex({
    id: 'cable_fly',
    name: 'Cable Fly',
    primaryMuscle: 'chest',
    secondaryMuscles: ['front_delts'],
    equipment: ['cable_machine'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Cable chest isolation with constant tension through the full arc.',
    setup: ['Set both pulleys near shoulder height.', 'Take a split stance with a slight forward lean.', 'Fix a soft elbow bend.'],
    execution: ['Bring the handles together in front of the chest.', 'Squeeze for a beat at peak contraction.', 'Return under control to a stretch.'],
    commonMistakes: ['Letting the arms straighten and shorten under load', 'Leaning too far forward', 'Rushing the eccentric'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 75,
    illustration: 'fly',
    loadFactor: 0.2,
  }),
  ex({
    id: 'pec_deck',
    name: 'Pec Deck',
    primaryMuscle: 'chest',
    secondaryMuscles: ['front_delts'],
    equipment: ['resistance_machines'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Machine fly with a fixed path, easy to take close to failure safely.',
    setup: ['Adjust the seat so the handles sit at chest height.', 'Place the back flat against the pad.', 'Grip the handles with the elbows slightly bent.'],
    execution: ['Bring the handles together in front of the chest.', 'Hold the squeeze for a moment.', 'Control the return to a stretch.'],
    commonMistakes: ['Seat set too low or high', 'Letting the shoulders roll forward', 'Slamming the weight stack'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 75,
    illustration: 'fly',
    loadFactor: 0.35,
  }),
  ex({
    id: 'chest_press_machine',
    name: 'Chest Press Machine',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'front_delts'],
    equipment: ['resistance_machines'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: true,
    category: 'push',
    instructions: 'Guided horizontal press — a safe way to accumulate pressing volume.',
    setup: ['Set the seat so the handles align with mid chest.', 'Press the back and shoulders into the pad.', 'Set the feet flat.'],
    execution: ['Press the handles out to a soft lockout.', 'Control the return until a light stretch is felt.', 'Keep the shoulder blades pinned throughout.'],
    commonMistakes: ['Seat height misaligned with the chest', 'Letting the shoulders round forward', 'Locking out aggressively'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 105,
    illustration: 'dumbbell_press',
    loadFactor: 0.6,
  }),
  ex({
    id: 'chest_dip',
    name: 'Chest Dips',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'front_delts'],
    equipment: ['dip_station', 'bodyweight'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'push',
    instructions: 'Chest-biased dip performed with a forward torso lean.',
    setup: ['Mount the bars with the arms locked.', 'Lean the torso forward around 30 degrees.', 'Cross the ankles behind you.'],
    execution: ['Lower until the upper arms are near parallel.', 'Keep the forward lean through the rep.', 'Press back up without fully shrugging at the top.'],
    commonMistakes: ['Descending too deep too early', 'Staying upright, which shifts the work to the triceps', 'Bouncing out of the bottom'],
    repRangeMin: 6,
    repRangeMax: 12,
    restSeconds: 120,
    illustration: 'dip',
    isBodyweight: true,
  }),
  ex({
    id: 'band_chest_press',
    name: 'Band Chest Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'front_delts'],
    equipment: ['resistance_bands'],
    availability: 'home',
    difficulty: 'beginner',
    isCompound: true,
    category: 'push',
    instructions: 'Standing band press for home training with no free weights.',
    setup: ['Anchor the band behind you at chest height.', 'Take a staggered stance with tension on the band.', 'Hold the handles at chest level.'],
    execution: ['Press the handles forward until the arms are extended.', 'Squeeze the chest at full extension.', 'Return slowly against the band tension.'],
    commonMistakes: ['Anchor too low or too high', 'Letting the band snap back', 'Shrugging through the press'],
    repRangeMin: 12,
    repRangeMax: 20,
    restSeconds: 60,
    illustration: 'dumbbell_press',
    isBodyweight: true,
  }),
  ex({
    id: 'smith_bench_press',
    name: 'Smith Machine Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'front_delts'],
    equipment: ['smith_machine', 'bench'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: true,
    category: 'push',
    instructions: 'Fixed-path bench press that can be trained hard without a spotter.',
    setup: ['Position the bench so the bar tracks over the mid chest.', 'Set the safety catches just below chest level.', 'Retract the shoulder blades.'],
    execution: ['Unhook and lower to the chest under control.', 'Keep the elbows at roughly 45 degrees.', 'Press back to lockout.'],
    commonMistakes: ['Bench positioned too far forward', 'Skipping the safety catches', 'Bouncing off the chest'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 120,
    illustration: 'barbell_press',
    loadFactor: 0.7,
  }),
  ex({
    id: 'feet_elevated_pushup',
    name: 'Feet-Elevated Push-up',
    primaryMuscle: 'chest',
    secondaryMuscles: ['front_delts', 'triceps', 'abs'],
    equipment: ['bodyweight'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'push',
    instructions: 'Push-up with the feet raised, shifting load onto the upper chest and shoulders.',
    setup: [
      'Place the feet on a chair, step or bed.',
      'Set the hands slightly wider than the shoulders under the upper chest.',
      'Brace the abs so the hips do not sag.',
    ],
    execution: [
      'Lower the chest toward the floor with the elbows at about 45 degrees.',
      'Stop when the upper arms reach parallel.',
      'Press away and hold the body in one straight line.',
    ],
    commonMistakes: ['Letting the hips pike upward', 'Flaring the elbows straight out', 'Dropping the head toward the floor first'],
    repRangeMin: 8,
    repRangeMax: 20,
    restSeconds: 90,
    illustration: 'incline_press',
    isBodyweight: true,
  }),
  ex({
    id: 'wide_pushup',
    name: 'Wide-Grip Push-up',
    primaryMuscle: 'chest',
    secondaryMuscles: ['front_delts'],
    equipment: ['bodyweight'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: true,
    category: 'push',
    instructions: 'Push-up with a wider hand position that biases the chest over the triceps.',
    setup: [
      'Set the hands about twice shoulder width apart.',
      'Turn the fingers slightly outward to spare the wrists.',
      'Squeeze the glutes to lock the body straight.',
    ],
    execution: [
      'Lower until the chest is just above the floor.',
      'Keep the elbows travelling out at roughly 60 degrees.',
      'Drive the floor away and stop just short of locking out.',
    ],
    commonMistakes: ['Going so wide the shoulders pinch', 'Letting the lower back arch', 'Shortening the range to add reps'],
    repRangeMin: 10,
    repRangeMax: 25,
    restSeconds: 75,
    illustration: 'pushup',
    isBodyweight: true,
  }),
];
