import type { Exercise } from '../types';
import { ex } from './builder';

export const QUAD_EXERCISES: Exercise[] = [
  ex({
    id: 'back_squat',
    name: 'Back Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings', 'lower_back', 'abs', 'adductors'],
    equipment: ['barbell', 'squat_rack', 'weight_plates'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'squat',
    instructions: 'The primary loaded squat pattern for lower-body size and strength.',
    setup: ['Set the bar on the upper back and take it out of the rack.', 'Stand with feet shoulder width, toes slightly out.', 'Brace the abs and set the ribs down.'],
    execution: ['Sit down and back, tracking the knees over the toes.', 'Descend to at least parallel.', 'Drive up through the whole foot to lockout.'],
    commonMistakes: ['Knees caving inward', 'Heels lifting off the floor', 'Letting the chest collapse forward'],
    repRangeMin: 6,
    repRangeMax: 10,
    restSeconds: 180,
    illustration: 'squat',
    loadFactor: 0.8,
  }),
  ex({
    id: 'front_squat',
    name: 'Front Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'abs', 'lower_back'],
    equipment: ['barbell', 'squat_rack', 'weight_plates'],
    availability: 'gym',
    difficulty: 'advanced',
    isCompound: true,
    category: 'squat',
    instructions: 'Front-racked squat with a more upright torso and greater quad demand.',
    setup: ['Rack the bar across the front delts with high elbows.', 'Take a shoulder-width stance.', 'Brace hard before unracking.'],
    execution: ['Descend with the torso as upright as possible.', 'Keep the elbows high throughout.', 'Drive up without letting the elbows drop.'],
    commonMistakes: ['Elbows dropping and the bar rolling forward', 'Rounding the upper back', 'Rising hips first out of the hole'],
    repRangeMin: 5,
    repRangeMax: 8,
    restSeconds: 180,
    illustration: 'front_squat',
    loadFactor: 0.6,
  }),
  ex({
    id: 'goblet_squat',
    name: 'Goblet Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'abs', 'adductors'],
    equipment: ['dumbbells', 'kettlebell'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: true,
    category: 'squat',
    instructions: 'Front-loaded squat with a dumbbell or kettlebell — the best squat entry point.',
    setup: ['Hold the weight against the chest with both hands.', 'Stand with feet shoulder width, toes slightly out.', 'Brace the abs.'],
    execution: ['Squat down between the legs, keeping the chest tall.', 'Descend until the hips drop below the knees if mobility allows.', 'Drive up through the whole foot.'],
    commonMistakes: ['Letting the weight pull the torso forward', 'Knees collapsing in', 'Cutting the depth short'],
    repRangeMin: 8,
    repRangeMax: 15,
    restSeconds: 105,
    illustration: 'squat',
    loadFactor: 0.3,
  }),
  ex({
    id: 'leg_press',
    name: 'Leg Press',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings', 'adductors'],
    equipment: ['resistance_machines'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: true,
    category: 'squat',
    instructions: 'Machine leg press allowing heavy quad loading with minimal trunk fatigue.',
    setup: ['Set the feet shoulder width on the middle of the platform.', 'Press the lower back flat into the seat.', 'Release the safeties.'],
    execution: ['Lower until the knees reach roughly 90 degrees or slightly deeper.', 'Keep the lower back flat.', 'Press back up without locking the knees hard.'],
    commonMistakes: ['Lower back rounding off the seat at depth', 'Slamming into lockout', 'Placing the hands on the knees'],
    repRangeMin: 8,
    repRangeMax: 15,
    restSeconds: 150,
    illustration: 'leg_press',
    loadFactor: 1.6,
  }),
  ex({
    id: 'hack_squat',
    name: 'Hack Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'adductors'],
    equipment: ['resistance_machines'],
    availability: 'gym',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'squat',
    instructions: 'Guided squat machine that loads the quads hard through a deep range.',
    setup: ['Set the shoulders under the pads.', 'Place the feet mid-platform, shoulder width.', 'Brace and release the safeties.'],
    execution: ['Descend under control to at least parallel.', 'Keep the back flat against the pad.', 'Drive up through the whole foot.'],
    commonMistakes: ['Letting the hips lift off the pad', 'Knees caving in', 'Bouncing at the bottom'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 150,
    illustration: 'leg_press',
    loadFactor: 1.0,
  }),
  ex({
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings', 'abs'],
    equipment: ['dumbbells', 'bench', 'bodyweight'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'lunge',
    instructions: 'Rear-foot-elevated split squat — high stimulus per kilo loaded.',
    setup: ['Place the rear foot on a bench behind you.', 'Set the front foot far enough forward for a vertical shin at the bottom.', 'Hold dumbbells at the sides if loading.'],
    execution: ['Lower until the front thigh is near parallel.', 'Keep most of the weight on the front foot.', 'Drive up through the front heel.'],
    commonMistakes: ['Front foot too close to the bench', 'Pushing off the rear foot', 'Letting the front knee cave in'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 105,
    illustration: 'split_squat',
    loadFactor: 0.25,
    isUnilateral: true,
  }),
  ex({
    id: 'walking_lunge',
    name: 'Walking Lunge',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings', 'abs'],
    equipment: ['dumbbells', 'bodyweight'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: true,
    category: 'lunge',
    instructions: 'Travelling lunge that trains the legs unilaterally with a balance demand.',
    setup: ['Stand tall holding dumbbells at the sides.', 'Set the feet hip width.', 'Brace the trunk.'],
    execution: ['Step forward and lower the back knee toward the floor.', 'Drive through the front heel to stand.', 'Step straight into the next rep with the other leg.'],
    commonMistakes: ['Steps that are too short', 'Front knee collapsing inward', 'Leaning the torso far forward'],
    repRangeMin: 10,
    repRangeMax: 16,
    restSeconds: 105,
    illustration: 'lunge',
    loadFactor: 0.2,
    isUnilateral: true,
  }),
  ex({
    id: 'reverse_lunge',
    name: 'Reverse Lunge',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings', 'abs'],
    equipment: ['dumbbells', 'bodyweight'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: true,
    category: 'lunge',
    instructions: 'Stepping backward into the lunge, which is easier on the knees than forward lunges.',
    setup: ['Stand tall with the feet hip width.', 'Hold dumbbells at the sides if loading.', 'Brace the trunk.'],
    execution: ['Step back and lower the rear knee toward the floor.', 'Keep the weight over the front foot.', 'Drive through the front heel back to standing.'],
    commonMistakes: ['Stepping back too short', 'Crashing the back knee into the floor', 'Letting the torso rotate'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 105,
    illustration: 'lunge',
    loadFactor: 0.2,
    isUnilateral: true,
  }),
  ex({
    id: 'forward_lunge',
    name: 'Forward Lunge',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings', 'abs'],
    equipment: ['dumbbells', 'bodyweight'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: true,
    category: 'lunge',
    instructions: 'Stepping forward into the lunge, with a strong eccentric quad demand.',
    setup: ['Stand tall, feet hip width.', 'Hold dumbbells at the sides if loading.', 'Brace the abs.'],
    execution: ['Step forward and lower the back knee toward the floor.', 'Keep the front shin near vertical.', 'Push back to the start position.'],
    commonMistakes: ['Front knee travelling far past the toes', 'Landing heavily', 'Torso collapsing forward'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 105,
    illustration: 'lunge',
    loadFactor: 0.18,
    isUnilateral: true,
  }),
  ex({
    id: 'step_up',
    name: 'Step-Up',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: ['dumbbells', 'bench', 'step_platform', 'bodyweight'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: true,
    category: 'lunge',
    instructions: 'Single-leg step onto a box — simple, scalable and strongly transferable.',
    setup: ['Set a box or bench at roughly knee height.', 'Place one whole foot on the surface.', 'Hold dumbbells at the sides if loading.'],
    execution: ['Drive through the top foot to stand tall.', 'Avoid pushing off the bottom foot.', 'Lower under control to the floor.'],
    commonMistakes: ['Bouncing off the trailing foot', 'Box set too high for control', 'Letting the knee cave inward'],
    repRangeMin: 8,
    repRangeMax: 15,
    restSeconds: 90,
    illustration: 'step_up',
    loadFactor: 0.2,
    isUnilateral: true,
  }),
  ex({
    id: 'leg_extension',
    name: 'Leg Extension',
    primaryMuscle: 'quads',
    secondaryMuscles: [],
    equipment: ['resistance_machines'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Pure quad isolation with the rectus femoris fully loaded at lockout.',
    setup: ['Set the seat so the knees align with the pivot.', 'Place the shin pad just above the ankles.', 'Hold the handles and sit back.'],
    execution: ['Extend the knees to full lockout.', 'Pause briefly at the top.', 'Lower under control to a stretch.'],
    commonMistakes: ['Swinging the weight up with momentum', 'Lifting the hips off the seat', 'Pad positioned too high on the shin'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 75,
    illustration: 'leg_extension',
    loadFactor: 0.45,
  }),
  ex({
    id: 'split_squat',
    name: 'Split Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'abs'],
    equipment: ['dumbbells', 'bodyweight'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: true,
    category: 'lunge',
    instructions: 'Static split stance squat — the most stable single-leg variation.',
    setup: ['Take a long split stance.', 'Keep the torso upright.', 'Hold dumbbells at the sides if loading.'],
    execution: ['Lower the back knee toward the floor.', 'Keep the front shin near vertical.', 'Drive through the front heel to stand.'],
    commonMistakes: ['Stance too narrow front-to-back', 'Shifting weight onto the rear foot', 'Torso collapsing forward'],
    repRangeMin: 8,
    repRangeMax: 15,
    restSeconds: 90,
    illustration: 'split_squat',
    loadFactor: 0.22,
    isUnilateral: true,
  }),
  ex({
    id: 'smith_squat',
    name: 'Smith Machine Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['smith_machine'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: true,
    category: 'squat',
    instructions: 'Fixed-path squat that lets you push close to failure without a spotter.',
    setup: ['Set the bar on the upper back.', 'Walk the feet slightly forward of the bar.', 'Set the safety catches below depth.'],
    execution: ['Descend to at least parallel.', 'Keep the whole foot planted.', 'Press back to a soft lockout.'],
    commonMistakes: ['Feet too far forward, straining the knees backward', 'Skipping the safeties', 'Bouncing at the bottom'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 150,
    illustration: 'squat',
    loadFactor: 0.8,
  }),
  ex({
    id: 'bodyweight_squat',
    name: 'Bodyweight Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'abs'],
    equipment: ['bodyweight'],
    availability: 'home',
    difficulty: 'beginner',
    isCompound: true,
    category: 'squat',
    instructions: 'Unloaded squat for beginners and home sessions, progressed by reps and tempo.',
    setup: ['Stand with feet shoulder width, toes slightly out.', 'Reach the arms forward for balance.', 'Brace the abs.'],
    execution: ['Sit down and back to at least parallel.', 'Keep the chest tall and heels down.', 'Drive up to full extension.'],
    commonMistakes: ['Heels lifting', 'Knees caving inward', 'Rushing through the reps'],
    repRangeMin: 15,
    repRangeMax: 25,
    restSeconds: 60,
    illustration: 'squat',
    isBodyweight: true,
  }),
  ex({
    id: 'wall_sit',
    name: 'Wall Sit',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes'],
    equipment: ['bodyweight'],
    availability: 'home',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Isometric quad hold requiring no equipment at all.',
    setup: ['Set the back flat against a wall.', 'Walk the feet out and slide down to a 90 degree knee angle.', 'Keep the feet shoulder width.'],
    execution: ['Hold the position for the prescribed time.', 'Keep the weight in the heels.', 'Breathe steadily rather than holding the breath.'],
    commonMistakes: ['Sitting too high to create real tension', 'Resting the hands on the thighs', 'Holding the breath'],
    repRangeMin: 30,
    repRangeMax: 60,
    restSeconds: 60,
    illustration: 'squat',
    isBodyweight: true,
    isTimed: true,
  }),
];

export const HAMSTRING_EXERCISES: Exercise[] = [
  ex({
    id: 'romanian_deadlift',
    name: 'Romanian Deadlift',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'lower_back', 'back', 'forearms'],
    equipment: ['barbell', 'dumbbells', 'weight_plates'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'hinge',
    instructions: 'The core hip hinge for hamstring and glute development.',
    setup: ['Hold the bar at arms length against the thighs.', 'Set the feet hip width with soft knees.', 'Set the lats and brace the abs.'],
    execution: ['Push the hips back and lower the bar along the legs.', 'Stop when the hamstrings reach a strong stretch.', 'Drive the hips forward to stand tall.'],
    commonMistakes: ['Turning it into a squat by bending the knees', 'Rounding the lower back', 'Letting the bar drift away from the legs'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 150,
    illustration: 'rdl',
    loadFactor: 0.7,
  }),
  ex({
    id: 'stiff_leg_deadlift',
    name: 'Stiff-Leg Deadlift',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'lower_back', 'back'],
    equipment: ['barbell', 'weight_plates'],
    availability: 'both',
    difficulty: 'advanced',
    isCompound: true,
    category: 'hinge',
    instructions: 'Hinge with nearly straight legs and a deeper stretch than the Romanian deadlift.',
    setup: ['Stand with the bar over the mid-foot.', 'Set the knees almost straight.', 'Brace and set a flat back.'],
    execution: ['Hinge down with minimal knee bend.', 'Lower until the hamstrings limit the range.', 'Drive the hips forward to stand.'],
    commonMistakes: ['Rounding the back to reach the floor', 'Using a load that forces a rounded spine', 'Hyperextending at the top'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 150,
    illustration: 'rdl',
    loadFactor: 0.6,
  }),
  ex({
    id: 'lying_leg_curl',
    name: 'Lying Leg Curl',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['calves'],
    equipment: ['resistance_machines'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Prone knee-flexion isolation for the hamstrings.',
    setup: ['Lie face down with the knees just off the pad edge.', 'Set the ankle pad just above the heels.', 'Grip the handles.'],
    execution: ['Curl the heels toward the glutes.', 'Squeeze at the top.', 'Lower under control to a full stretch.'],
    commonMistakes: ['Lifting the hips off the pad', 'Using momentum to start each rep', 'Partial range at the bottom'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 75,
    illustration: 'leg_curl',
    loadFactor: 0.35,
  }),
  ex({
    id: 'seated_leg_curl',
    name: 'Seated Leg Curl',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['calves'],
    equipment: ['resistance_machines'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Seated knee flexion with the hips flexed, which lengthens the hamstrings.',
    setup: ['Set the back pad so the knees align with the pivot.', 'Lock the thigh pad down.', 'Sit tall and grip the handles.'],
    execution: ['Curl the heels down and back.', 'Hold the contraction briefly.', 'Return under control to a full stretch.'],
    commonMistakes: ['Thigh pad too loose', 'Sliding the hips forward', 'Letting the stack drop'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 75,
    illustration: 'leg_curl',
    loadFactor: 0.35,
  }),
  ex({
    id: 'standing_leg_curl',
    name: 'Leg Curl',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['calves'],
    equipment: ['resistance_machines', 'cable_machine'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Single-leg standing knee flexion, useful for evening out side-to-side differences.',
    setup: ['Set the pad against the back of one ankle.', 'Stand tall and hold the support.', 'Keep the working thigh still.'],
    execution: ['Curl the heel toward the glute.', 'Squeeze at the top.', 'Lower under control.'],
    commonMistakes: ['Swinging the hip to assist', 'Arching the lower back', 'Rushing the return'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 60,
    illustration: 'leg_curl',
    loadFactor: 0.2,
    isUnilateral: true,
  }),
  ex({
    id: 'nordic_curl',
    name: 'Nordic Curl',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'abs'],
    equipment: ['bodyweight'],
    availability: 'both',
    difficulty: 'advanced',
    isCompound: false,
    category: 'isolation',
    instructions: 'Bodyweight eccentric hamstring curl — extremely demanding, highly effective.',
    setup: ['Kneel on a pad with the ankles anchored.', 'Keep the hips extended in line with the torso.', 'Cross the arms over the chest.'],
    execution: ['Lower the torso forward as slowly as possible.', 'Catch with the hands when control is lost.', 'Push back up and use the hamstrings as far as possible.'],
    commonMistakes: ['Breaking at the hips instead of the knees', 'Dropping fast rather than resisting', 'Attempting full reps before building the eccentric'],
    repRangeMin: 3,
    repRangeMax: 8,
    restSeconds: 120,
    illustration: 'leg_curl',
    isBodyweight: true,
  }),
  ex({
    id: 'good_morning',
    name: 'Good Morning',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'lower_back', 'back'],
    equipment: ['barbell', 'squat_rack', 'weight_plates'],
    availability: 'gym',
    difficulty: 'advanced',
    isCompound: true,
    category: 'hinge',
    instructions: 'Barbell hinge with the bar on the back, loading the hamstrings and erectors.',
    setup: ['Place the bar on the upper back as in a squat.', 'Set the feet hip width with soft knees.', 'Brace hard.'],
    execution: ['Push the hips back and hinge the torso forward.', 'Stop at about parallel or when the hamstrings limit range.', 'Drive the hips forward to stand.'],
    commonMistakes: ['Rounding the back', 'Going too heavy too early', 'Bending the knees to reach depth'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 120,
    illustration: 'good_morning',
    loadFactor: 0.4,
  }),
  ex({
    id: 'single_leg_rdl',
    name: 'Single-Leg Romanian Deadlift',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'lower_back', 'abs'],
    equipment: ['dumbbells', 'kettlebell', 'bodyweight'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'hinge',
    instructions: 'Unilateral hinge that builds hamstring strength and hip stability together.',
    setup: ['Stand on one leg with a soft knee.', 'Hold a dumbbell in the opposite hand.', 'Set the shoulders square.'],
    execution: ['Hinge forward, letting the rear leg rise behind you.', 'Keep the hips square to the floor.', 'Return to standing by driving the hip forward.'],
    commonMistakes: ['Rotating the hip open', 'Rounding the back', 'Rushing and losing balance'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 90,
    illustration: 'rdl',
    loadFactor: 0.25,
    isUnilateral: true,
  }),
  ex({
    id: 'band_leg_curl',
    name: 'Band Leg Curl',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: [],
    equipment: ['resistance_bands'],
    availability: 'home',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Prone band curl replacing the machine for home training.',
    setup: ['Anchor the band low behind you.', 'Lie face down and loop the band around the ankles.', 'Set light tension at the start.'],
    execution: ['Curl the heels toward the glutes.', 'Squeeze at the top.', 'Return slowly against the band.'],
    commonMistakes: ['Lifting the hips', 'Letting the band snap the legs back', 'Anchoring the band too high'],
    repRangeMin: 15,
    repRangeMax: 25,
    restSeconds: 50,
    illustration: 'leg_curl',
    isBodyweight: true,
  }),
  ex({
    id: 'glute_ham_raise',
    name: 'Glute-Ham Raise',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'lower_back'],
    equipment: ['resistance_machines'],
    availability: 'gym',
    difficulty: 'advanced',
    isCompound: true,
    category: 'hinge',
    instructions: 'Machine-based hamstring curl combining hip extension and knee flexion.',
    setup: ['Set the foot plate so the knees sit just behind the pad.', 'Lock the ankles in.', 'Start with the torso upright.'],
    execution: ['Lower the torso under control to horizontal.', 'Curl back up using the hamstrings.', 'Keep the hips extended throughout.'],
    commonMistakes: ['Breaking at the hips to make it easier', 'Dropping rather than resisting the descent', 'Pad set too far from the knees'],
    repRangeMin: 6,
    repRangeMax: 10,
    restSeconds: 105,
    illustration: 'leg_curl',
    isBodyweight: true,
  }),
];

export const GLUTE_EXERCISES: Exercise[] = [
  ex({
    id: 'hip_thrust',
    name: 'Hip Thrust',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings', 'quads'],
    equipment: ['bench', 'dumbbells', 'bodyweight'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: true,
    category: 'hinge',
    instructions: 'Bench-supported hip extension — the highest-tension glute exercise at lockout.',
    setup: ['Sit with the upper back against a bench edge.', 'Place a dumbbell across the hips if loading.', 'Set the feet so the shins are vertical at the top.'],
    execution: ['Drive the hips up until the torso is parallel to the floor.', 'Squeeze the glutes hard at lockout.', 'Lower under control without resting.'],
    commonMistakes: ['Hyperextending the lower back at the top', 'Feet too far forward or back', 'Pushing through the toes'],
    repRangeMin: 8,
    repRangeMax: 15,
    restSeconds: 105,
    illustration: 'hip_thrust',
    loadFactor: 0.4,
  }),
  ex({
    id: 'barbell_hip_thrust',
    name: 'Barbell Hip Thrust',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings', 'quads'],
    equipment: ['barbell', 'bench', 'weight_plates'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'hinge',
    instructions: 'Heavily loaded hip thrust for maximal glute strength.',
    setup: ['Roll the bar over the hips with a pad in place.', 'Set the upper back on the bench edge.', 'Tuck the chin and brace the abs.'],
    execution: ['Drive the hips to full extension.', 'Hold the lockout for a beat.', 'Lower under control just short of the floor.'],
    commonMistakes: ['Arching the lower back instead of extending the hips', 'Letting the chin lift at lockout', 'Bouncing the bar off the floor'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 150,
    illustration: 'hip_thrust',
    loadFactor: 0.9,
  }),
  ex({
    id: 'glute_bridge',
    name: 'Glute Bridge',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings', 'abs'],
    equipment: ['bodyweight'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'hinge',
    instructions: 'Floor-based hip extension, the entry point to glute training.',
    setup: ['Lie on the back with the knees bent and feet flat.', 'Place the arms at the sides.', 'Tuck the pelvis slightly.'],
    execution: ['Drive the hips up until the body forms a straight line.', 'Squeeze the glutes at the top.', 'Lower under control.'],
    commonMistakes: ['Arching the lower back instead of squeezing the glutes', 'Feet too far from the hips', 'Rushing the reps'],
    repRangeMin: 15,
    repRangeMax: 25,
    restSeconds: 60,
    illustration: 'glute_bridge',
    isBodyweight: true,
  }),
  ex({
    id: 'single_leg_glute_bridge',
    name: 'Single-Leg Glute Bridge',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings', 'abs'],
    equipment: ['bodyweight'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'hinge',
    instructions: 'Unilateral bridge that doubles the load per glute without equipment.',
    setup: ['Lie on the back with one knee bent, foot flat.', 'Extend the other leg or hug the knee.', 'Set the pelvis neutral.'],
    execution: ['Drive the hips up through the planted heel.', 'Keep the hips level throughout.', 'Lower under control.'],
    commonMistakes: ['Hips tilting to one side', 'Arching the back to gain height', 'Pushing through the toes'],
    repRangeMin: 10,
    repRangeMax: 20,
    restSeconds: 60,
    illustration: 'glute_bridge',
    isBodyweight: true,
    isUnilateral: true,
  }),
  ex({
    id: 'cable_kickback',
    name: 'Cable Kickback',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: ['cable_machine'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Single-leg hip extension against a cable for direct glute isolation.',
    setup: ['Attach an ankle strap to the low pulley.', 'Face the machine and hold the frame.', 'Hinge slightly forward at the hips.'],
    execution: ['Drive the working leg back and up.', 'Squeeze the glute at the top.', 'Return under control without swinging.'],
    commonMistakes: ['Arching the lower back to gain range', 'Swinging the leg with momentum', 'Rotating the hips open'],
    repRangeMin: 12,
    repRangeMax: 20,
    restSeconds: 60,
    illustration: 'kickback',
    loadFactor: 0.12,
    isUnilateral: true,
  }),
  ex({
    id: 'hip_abduction',
    name: 'Hip Abduction',
    primaryMuscle: 'glutes',
    secondaryMuscles: [],
    equipment: ['resistance_machines'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Machine abduction targeting the gluteus medius.',
    setup: ['Sit with the pads against the outer thighs.', 'Set a comfortable starting width.', 'Sit tall or lean slightly forward.'],
    execution: ['Push the knees apart to full range.', 'Hold the contraction briefly.', 'Return slowly against resistance.'],
    commonMistakes: ['Using the torso to force the pads open', 'Letting the stack slam back', 'Bouncing the reps'],
    repRangeMin: 12,
    repRangeMax: 20,
    restSeconds: 60,
    illustration: 'abduction',
    loadFactor: 0.35,
  }),
  ex({
    id: 'banded_hip_abduction',
    name: 'Banded Hip Abduction',
    primaryMuscle: 'glutes',
    secondaryMuscles: [],
    equipment: ['resistance_bands'],
    availability: 'home',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Seated or side-lying band abduction for the gluteus medius at home.',
    setup: ['Loop a band just above the knees.', 'Sit on a bench or lie on the side.', 'Set light tension at the start.'],
    execution: ['Push the knees apart against the band.', 'Hold the end position briefly.', 'Return slowly.'],
    commonMistakes: ['Letting the band snap the knees together', 'Rocking the torso', 'Using a band that is far too light'],
    repRangeMin: 15,
    repRangeMax: 30,
    restSeconds: 45,
    illustration: 'abduction',
    isBodyweight: true,
  }),
  ex({
    id: 'kettlebell_swing',
    name: 'Kettlebell Swing',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings', 'back', 'abs', 'lower_back'],
    equipment: ['kettlebell'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'hinge',
    instructions: 'Ballistic hip hinge that trains explosive hip extension and conditioning.',
    setup: ['Set the kettlebell a foot in front of you.', 'Hinge and hike it back between the legs.', 'Set a flat back and braced trunk.'],
    execution: ['Snap the hips forward to float the bell to chest height.', 'Keep the arms relaxed — the hips do the work.', 'Guide the bell back into the next hinge.'],
    commonMistakes: ['Squatting instead of hinging', 'Lifting the bell with the arms', 'Rounding the back at the bottom'],
    repRangeMin: 12,
    repRangeMax: 20,
    restSeconds: 75,
    illustration: 'swing',
    loadFactor: 0.25,
  }),
  ex({
    id: 'curtsy_lunge',
    name: 'Curtsy Lunge',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['quads', 'adductors'],
    equipment: ['dumbbells', 'bodyweight'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'lunge',
    instructions: 'Cross-behind lunge that emphasises the gluteus medius.',
    setup: ['Stand tall with the feet hip width.', 'Hold dumbbells at the sides if loading.', 'Brace the abs.'],
    execution: ['Step one leg back and across behind the other.', 'Lower until the front thigh nears parallel.', 'Drive back to standing through the front heel.'],
    commonMistakes: ['Letting the front knee cave inward', 'Twisting the torso', 'Stepping too far across'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 90,
    illustration: 'lunge',
    loadFactor: 0.18,
    isUnilateral: true,
  }),
  ex({
    id: 'sumo_deadlift',
    name: 'Sumo Deadlift',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['quads', 'hamstrings', 'back', 'adductors', 'forearms'],
    equipment: ['barbell', 'weight_plates'],
    availability: 'both',
    difficulty: 'advanced',
    isCompound: true,
    category: 'hinge',
    instructions: 'Wide-stance deadlift with more hip and quad involvement and a shorter range.',
    setup: ['Take a wide stance with the toes turned out.', 'Grip inside the knees.', 'Drop the hips and set a flat back.'],
    execution: ['Push the floor apart and drive the hips through.', 'Keep the bar against the legs.', 'Lock out tall, then lower under control.'],
    commonMistakes: ['Hips rising before the bar leaves the floor', 'Knees caving in', 'Rounding the upper back'],
    repRangeMin: 4,
    repRangeMax: 8,
    restSeconds: 180,
    illustration: 'deadlift',
    loadFactor: 1.0,
  }),
  ex({
    id: 'frog_pump',
    name: 'Frog Pump',
    primaryMuscle: 'glutes',
    secondaryMuscles: [],
    equipment: ['bodyweight', 'dumbbells'],
    availability: 'home',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'High-rep glute bridge variation with the feet together and knees out.',
    setup: ['Lie on the back with the soles of the feet together.', 'Let the knees fall out to the sides.', 'Place a dumbbell on the hips if loading.'],
    execution: ['Drive the hips up and squeeze the glutes.', 'Hold the top for a beat.', 'Lower just short of the floor.'],
    commonMistakes: ['Arching the lower back', 'Letting the knees come together', 'Rushing through the reps'],
    repRangeMin: 15,
    repRangeMax: 30,
    restSeconds: 50,
    illustration: 'glute_bridge',
    loadFactor: 0.25,
  }),
];

export const CALF_EXERCISES: Exercise[] = [
  ex({
    id: 'standing_calf_raise',
    name: 'Standing Calf Raise',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: ['resistance_machines', 'smith_machine', 'dumbbells', 'bodyweight'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Straight-leg calf raise that biases the gastrocnemius.',
    setup: ['Stand with the balls of the feet on a step or platform.', 'Keep the knees nearly straight.', 'Stand tall with the trunk braced.'],
    execution: ['Rise as high onto the toes as possible.', 'Pause at the top.', 'Lower slowly to a deep stretch.'],
    commonMistakes: ['Bouncing out of the bottom', 'Bending the knees to gain height', 'Cutting the range short at both ends'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 60,
    illustration: 'calf_raise',
    loadFactor: 0.6,
  }),
  ex({
    id: 'seated_calf_raise',
    name: 'Seated Calf Raise',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: ['resistance_machines'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Bent-knee calf raise that targets the soleus.',
    setup: ['Sit with the balls of the feet on the platform.', 'Lock the thigh pad just above the knees.', 'Release the safety lever.'],
    execution: ['Press up onto the toes as high as possible.', 'Hold the peak contraction.', 'Lower slowly to a deep stretch.'],
    commonMistakes: ['Half reps', 'Bouncing the stack', 'Pad positioned too far forward on the thighs'],
    repRangeMin: 12,
    repRangeMax: 20,
    restSeconds: 60,
    illustration: 'calf_raise',
    loadFactor: 0.4,
  }),
  ex({
    id: 'single_leg_calf_raise',
    name: 'Single-Leg Calf Raise',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: ['bodyweight', 'dumbbells'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Unilateral calf raise doubling the load per side with no machine required.',
    setup: ['Stand on one foot on a step, holding a support.', 'Let the heel drop below the step.', 'Hold a dumbbell in the free hand if loading.'],
    execution: ['Rise onto the toes as high as possible.', 'Pause at the top.', 'Lower slowly to a full stretch.'],
    commonMistakes: ['Pulling on the support to assist', 'Short range of motion', 'Rushing the reps'],
    repRangeMin: 12,
    repRangeMax: 20,
    restSeconds: 50,
    illustration: 'calf_raise',
    loadFactor: 0.2,
    isUnilateral: true,
  }),
  ex({
    id: 'leg_press_calf_raise',
    name: 'Leg Press Calf Raise',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: ['resistance_machines'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Calf raise performed on the leg press platform, easy to load heavily.',
    setup: ['Place the balls of the feet at the bottom edge of the platform.', 'Keep the knees nearly straight.', 'Leave the safeties engaged.'],
    execution: ['Press the platform away by extending the ankles.', 'Pause at full extension.', 'Return slowly to a deep stretch.'],
    commonMistakes: ['Bending the knees to press the weight', 'Letting the feet slip on the platform', 'Very short reps'],
    repRangeMin: 12,
    repRangeMax: 20,
    restSeconds: 60,
    illustration: 'calf_raise',
    loadFactor: 1.0,
  }),
  ex({
    id: 'donkey_calf_raise',
    name: 'Donkey Calf Raise',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: ['resistance_machines', 'bodyweight'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: false,
    category: 'isolation',
    instructions: 'Bent-over calf raise that puts the gastrocnemius in a stretched hip position.',
    setup: ['Hinge forward and support the upper body on a bench.', 'Place the balls of the feet on a step.', 'Keep the knees nearly straight.'],
    execution: ['Rise onto the toes as high as possible.', 'Pause at the top.', 'Lower slowly to a full stretch.'],
    commonMistakes: ['Rounding the back heavily', 'Bouncing the reps', 'Bending the knees'],
    repRangeMin: 12,
    repRangeMax: 20,
    restSeconds: 60,
    illustration: 'calf_raise',
    isBodyweight: true,
  }),
  ex({
    id: 'smith_calf_raise',
    name: 'Smith Machine Calf Raise',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: ['smith_machine', 'step_platform'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Standing calf raise under a fixed bar path, simple to load and progress.',
    setup: ['Set a step under the bar.', 'Place the bar on the upper back and the balls of the feet on the step.', 'Unhook the bar.'],
    execution: ['Rise onto the toes to full extension.', 'Hold briefly at the top.', 'Lower slowly to a deep stretch.'],
    commonMistakes: ['Bending the knees', 'Partial reps', 'Step positioned poorly under the bar'],
    repRangeMin: 12,
    repRangeMax: 20,
    restSeconds: 60,
    illustration: 'calf_raise',
    loadFactor: 0.7,
  }),
];
