import type { Exercise } from '../types';
import { ex } from './builder';

export const SHOULDER_EXERCISES: Exercise[] = [
  ex({
    id: 'overhead_press',
    name: 'Overhead Press',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps', 'abs', 'chest'],
    equipment: ['barbell', 'weight_plates'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'push',
    instructions: 'Standing barbell press overhead — the core vertical pressing strength movement.',
    setup: ['Take the bar at shoulder height with a grip just outside the shoulders.', 'Stand with feet hip width, glutes and abs braced.', 'Set the elbows slightly in front of the bar.'],
    execution: ['Press the bar straight up, moving the head back out of the path.', 'Lock out with the bar over the mid-foot.', 'Lower under control to the front delts.'],
    commonMistakes: ['Leaning back excessively', 'Pressing around the head instead of moving the head', 'Losing the trunk brace'],
    repRangeMin: 6,
    repRangeMax: 10,
    restSeconds: 150,
    illustration: 'overhead_press',
    loadFactor: 0.45,
  }),
  ex({
    id: 'seated_barbell_press',
    name: 'Barbell Shoulder Press',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps', 'chest'],
    equipment: ['barbell', 'bench', 'squat_rack', 'weight_plates'],
    availability: 'gym',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'push',
    instructions: 'Seated barbell press, removing leg drive so the delts do the work.',
    setup: ['Set an upright bench inside a rack.', 'Grip the bar just outside shoulder width.', 'Sit tall with the back against the pad.'],
    execution: ['Press the bar overhead to lockout.', 'Keep the ribs down and the abs braced.', 'Lower to chin height under control.'],
    commonMistakes: ['Arching the lower back hard off the pad', 'Bouncing the bar off the chest', 'Flaring the elbows wide at the bottom'],
    repRangeMin: 6,
    repRangeMax: 10,
    restSeconds: 150,
    illustration: 'overhead_press',
    loadFactor: 0.45,
  }),
  ex({
    id: 'dumbbell_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbells', 'bench'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: true,
    category: 'push',
    instructions: 'Vertical dumbbell press with a natural arm path and per-side balance.',
    setup: ['Sit with back support or stand tall.', 'Start with the dumbbells at ear height.', 'Set the elbows slightly in front of the body.'],
    execution: ['Press up until the arms are extended.', 'Keep the dumbbells over the elbows.', 'Lower to ear height with control.'],
    commonMistakes: ['Letting the elbows drift far behind the body', 'Clashing the dumbbells overhead', 'Losing the trunk brace'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 120,
    illustration: 'overhead_press',
    loadFactor: 0.2,
  }),
  ex({
    id: 'arnold_press',
    name: 'Arnold Press',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps', 'chest'],
    equipment: ['dumbbells', 'bench'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'push',
    instructions: 'Rotating dumbbell press that covers front and side delt fibres in one path.',
    setup: ['Start with the dumbbells at chest height, palms facing you.', 'Sit or stand tall with a braced trunk.', 'Keep the elbows close to the body.'],
    execution: ['Rotate the palms outward as you press up.', 'Finish with the arms extended, palms forward.', 'Reverse the rotation on the way down.'],
    commonMistakes: ['Rotating too late in the press', 'Using excessive weight and losing control', 'Arching the lower back'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 105,
    illustration: 'overhead_press',
    loadFactor: 0.16,
  }),
  ex({
    id: 'lateral_raise',
    name: 'Lateral Raise',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['traps'],
    equipment: ['dumbbells'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'The key side-delt isolation for shoulder width.',
    setup: ['Stand with the dumbbells at the sides, a slight forward lean.', 'Fix a small elbow bend.', 'Brace the trunk.'],
    execution: ['Raise the arms out to shoulder height.', 'Lead with the elbows, not the hands.', 'Lower slowly under control.'],
    commonMistakes: ['Swinging with the hips', 'Raising far above shoulder height', 'Shrugging the traps to finish the rep'],
    repRangeMin: 12,
    repRangeMax: 18,
    restSeconds: 60,
    illustration: 'lateral_raise',
    loadFactor: 0.08,
  }),
  ex({
    id: 'cable_lateral_raise',
    name: 'Cable Lateral Raise',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['traps'],
    equipment: ['cable_machine'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Side-delt isolation with tension held through the bottom of the range.',
    setup: ['Set the pulley to the lowest position.', 'Stand side-on and take the handle in the outside hand.', 'Start with the handle across the front of the body.'],
    execution: ['Raise the arm out to shoulder height.', 'Keep a fixed soft elbow bend.', 'Lower slowly, resisting the cable.'],
    commonMistakes: ['Leaning away to gain leverage', 'Bending the elbow through the rep', 'Going too heavy and shrugging'],
    repRangeMin: 12,
    repRangeMax: 18,
    restSeconds: 60,
    illustration: 'lateral_raise',
    loadFactor: 0.08,
    isUnilateral: true,
  }),
  ex({
    id: 'band_lateral_raise',
    name: 'Band Lateral Raise',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['traps'],
    equipment: ['resistance_bands'],
    availability: 'home',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Band side raise for home sessions without dumbbells.',
    setup: ['Stand on the middle of the band.', 'Hold a handle in each hand at the sides.', 'Stand tall with a braced trunk.'],
    execution: ['Raise the arms out to shoulder height.', 'Pause briefly at the top.', 'Lower slowly against the band.'],
    commonMistakes: ['Letting the band snap the arms down', 'Raising above shoulder height', 'Bouncing through the reps'],
    repRangeMin: 15,
    repRangeMax: 25,
    restSeconds: 50,
    illustration: 'lateral_raise',
    isBodyweight: true,
  }),
  ex({
    id: 'front_raise',
    name: 'Front Raise',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['front_delts', 'chest'],
    equipment: ['dumbbells'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Front-delt isolation, used sparingly since pressing already trains this head.',
    setup: ['Hold the dumbbells in front of the thighs.', 'Stand tall with the abs braced.', 'Set a slight elbow bend.'],
    execution: ['Raise one or both arms to shoulder height.', 'Keep the wrists neutral.', 'Lower under control.'],
    commonMistakes: ['Swinging the torso', 'Raising well above shoulder height', 'Using momentum from the knees'],
    repRangeMin: 12,
    repRangeMax: 15,
    restSeconds: 60,
    illustration: 'front_raise',
    loadFactor: 0.08,
  }),
  ex({
    id: 'rear_delt_fly',
    name: 'Rear Delt Fly',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['rear_delts', 'back', 'traps'],
    equipment: ['dumbbells'],
    availability: 'both',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Rear-delt isolation that balances heavy pressing volume.',
    setup: ['Hinge forward to roughly 45 degrees or lie chest-down on an incline.', 'Let the dumbbells hang under the shoulders.', 'Fix a soft elbow bend.'],
    execution: ['Raise the arms out to the sides.', 'Lead with the elbows and stop level with the torso.', 'Lower slowly to the stretch.'],
    commonMistakes: ['Turning it into a row', 'Using the lower back to swing the weight', 'Shrugging at the top'],
    repRangeMin: 12,
    repRangeMax: 18,
    restSeconds: 60,
    illustration: 'rear_delt',
    loadFactor: 0.07,
  }),
  ex({
    id: 'reverse_pec_deck',
    name: 'Reverse Pec Deck',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['rear_delts', 'back'],
    equipment: ['resistance_machines'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Machine rear-delt fly with a fixed path and consistent tension.',
    setup: ['Face the pad and set the handles to shoulder height.', 'Keep the chest against the pad.', 'Grip the handles with a soft elbow bend.'],
    execution: ['Open the arms back and out.', 'Squeeze the rear delts briefly.', 'Return under control without letting the stack rest.'],
    commonMistakes: ['Pulling with the arms bent like a row', 'Lifting the chest off the pad', 'Overloading and shortening the range'],
    repRangeMin: 12,
    repRangeMax: 18,
    restSeconds: 60,
    illustration: 'rear_delt',
    loadFactor: 0.2,
  }),
  ex({
    id: 'face_pull',
    name: 'Face Pull',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['rear_delts', 'back', 'traps'],
    equipment: ['cable_machine'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: false,
    category: 'isolation',
    instructions: 'Upper-back and rear-delt work that supports healthy pressing mechanics.',
    setup: ['Set the pulley just above head height with a rope attachment.', 'Step back until there is tension.', 'Start with the arms extended.'],
    execution: ['Pull the rope toward the forehead, hands separating.', 'Finish with the elbows high and wide.', 'Return slowly to full extension.'],
    commonMistakes: ['Pulling too low, turning it into a row', 'Leaning back to move the weight', 'Rushing the return'],
    repRangeMin: 12,
    repRangeMax: 20,
    restSeconds: 60,
    illustration: 'face_pull',
    loadFactor: 0.2,
  }),
  ex({
    id: 'machine_shoulder_press',
    name: 'Machine Shoulder Press',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: ['resistance_machines'],
    availability: 'gym',
    difficulty: 'beginner',
    isCompound: true,
    category: 'push',
    instructions: 'Guided overhead press, a safe way to add pressing volume late in a session.',
    setup: ['Set the seat so the handles sit at shoulder height.', 'Press the back into the pad.', 'Grip the handles with the wrists neutral.'],
    execution: ['Press overhead to a soft lockout.', 'Control the descent to shoulder height.', 'Keep the ribs down throughout.'],
    commonMistakes: ['Seat set too low', 'Bouncing at the bottom', 'Letting the lower back arch off the pad'],
    repRangeMin: 8,
    repRangeMax: 12,
    restSeconds: 105,
    illustration: 'overhead_press',
    loadFactor: 0.4,
  }),
  ex({
    id: 'upright_row',
    name: 'Upright Row',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['traps', 'biceps', 'forearms'],
    equipment: ['barbell', 'ez_bar', 'dumbbells'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'pull',
    instructions: 'Vertical pull for the side delts and traps, performed to chest height only.',
    setup: ['Hold the bar at shoulder width in front of the thighs.', 'Stand tall with a braced trunk.', 'Relax the shoulders down.'],
    execution: ['Pull the bar up to the lower chest, elbows leading.', 'Stop before the elbows pass shoulder height.', 'Lower under control.'],
    commonMistakes: ['Pulling to the chin with a narrow grip', 'Using the hips to swing the bar', 'Letting the wrists bend sharply'],
    repRangeMin: 10,
    repRangeMax: 15,
    restSeconds: 75,
    illustration: 'shrug',
    loadFactor: 0.25,
  }),
  ex({
    id: 'pike_push_up',
    name: 'Pike Push-ups',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps', 'front_delts'],
    equipment: ['bodyweight'],
    availability: 'home',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'push',
    instructions: 'Bodyweight vertical press for home training without dumbbells.',
    setup: ['Start in a push-up position and walk the feet in.', 'Pike the hips high so the torso is near vertical.', 'Set the hands slightly wider than shoulders.'],
    execution: ['Lower the crown of the head toward the floor.', 'Keep the elbows moderately tucked.', 'Press back to full extension.'],
    commonMistakes: ['Letting the hips drop into a push-up', 'Flaring the elbows wide', 'Rushing the descent'],
    repRangeMin: 8,
    repRangeMax: 15,
    restSeconds: 75,
    illustration: 'overhead_press',
    isBodyweight: true,
  }),
  ex({
    id: 'elevated_pike_pushup',
    name: 'Elevated Pike Push-up',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps', 'chest'],
    equipment: ['bodyweight'],
    availability: 'both',
    difficulty: 'intermediate',
    isCompound: true,
    category: 'push',
    instructions: 'Pike push-up with the feet raised, bringing the angle closer to a true overhead press.',
    setup: [
      'Place the feet on a chair or step and walk the hands back.',
      'Pike the hips high so the torso is close to vertical.',
      'Set the hands just wider than the shoulders.',
    ],
    execution: [
      'Lower the crown of the head toward the floor between the hands.',
      'Keep the elbows tracking forward, not flaring wide.',
      'Press back up until the arms are straight.',
    ],
    commonMistakes: ['Letting the hips drop into a push-up', 'Lowering the head in front of the hands', 'Cutting the depth short'],
    repRangeMin: 6,
    repRangeMax: 12,
    restSeconds: 90,
    illustration: 'overhead_press',
    isBodyweight: true,
  }),
  ex({
    id: 'wall_handstand_hold',
    name: 'Wall Handstand Hold',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps', 'abs'],
    equipment: ['bodyweight'],
    availability: 'both',
    difficulty: 'advanced',
    isCompound: true,
    category: 'push',
    instructions: 'Inverted isometric hold that loads the shoulders with full bodyweight.',
    setup: [
      'Place the hands about 20 cm from a clear wall.',
      'Walk the feet up the wall until the body is near vertical.',
      'Stack the wrists, shoulders and hips in one line.',
    ],
    execution: [
      'Hold the position with the ribs down and the glutes squeezed.',
      'Push the floor away to keep the shoulders active.',
      'Come down under control before form breaks.',
    ],
    commonMistakes: ['Arching the lower back away from the wall', 'Sinking into the shoulders', 'Holding the breath'],
    repRangeMin: 20,
    repRangeMax: 60,
    restSeconds: 90,
    illustration: 'overhead_press',
    isBodyweight: true,
    isTimed: true,
  }),
  ex({
    id: 'pseudo_planche_pushup',
    name: 'Pseudo Planche Push-up',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['chest', 'triceps', 'abs'],
    equipment: ['bodyweight'],
    availability: 'both',
    difficulty: 'advanced',
    isCompound: true,
    category: 'push',
    instructions: 'Push-up with the hands set low and the torso leaning forward, loading the front delts hard.',
    setup: [
      'Set the hands beside the waist with the fingers turned out.',
      'Lean the shoulders well forward of the hands.',
      'Lock the body straight from head to heels.',
    ],
    execution: [
      'Lower while keeping the forward lean.',
      'Keep the elbows close and pointing back.',
      'Press up without letting the shoulders drift behind the hands.',
    ],
    commonMistakes: ['Losing the forward lean mid-rep', 'Letting the hips pike up', 'Attempting these before pike push-ups are easy'],
    repRangeMin: 5,
    repRangeMax: 12,
    restSeconds: 90,
    illustration: 'pushup',
    isBodyweight: true,
  }),
];
