/**
 * Injecting the deployment-target hook into the generated Podfile.
 *
 * Xcode 27 refuses to build a target that deploys below its supported range,
 * and several pods still declare 13.4 — including their resource bundle
 * targets, which are separate targets and the ones people miss. `ios/` is
 * regenerated by every prebuild, so the fix has to be re-applied there rather
 * than corrected by hand in Xcode.
 */
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { describe, test } from 'node:test';

const plugin = createRequire(__filename)('../plugins/withPodDeploymentTarget') as {
  withDeploymentTargetHook: (podfile: string, deploymentTarget: string) => string;
  configuredTarget: (config: { plugins?: unknown[] }) => string | null;
};
const { withDeploymentTargetHook, configuredTarget } = plugin;

/**
 * Shaped like the Podfile Expo generates, nested blocks and all.
 *
 * The nesting is the point: the resource-bundle loop ends with four `end`s in
 * a row, and the first of them is not the end of post_install.
 */
const PODFILE = `require File.join(File.dirname(\`node --print "require.resolve('expo/package.json')"\`), "scripts/autolinking")

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'

target 'GetFit' do
  use_expo_modules!

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end
`;

const lineOf = (text: string, needle: string): number =>
  text.split('\n').findIndex((line) => line.includes(needle));

describe('finding where the block belongs', () => {
  const updated = withDeploymentTargetHook(PODFILE, '15.1');

  test('the hook lands inside post_install', () => {
    const open = lineOf(updated, 'post_install do |installer|');
    const hook = lineOf(updated, 'getfit_minimum');
    const close = updated.split('\n').findIndex((line, i) => i > open && line === '  end');
    assert.ok(hook > open && hook < close, 'the hook escaped the post_install block');
  });

  test('it closes the post_install block, with no loop still open after it', () => {
    // The discriminating check. Matching the nearest `end` puts the hook
    // inside the resource-bundle loop — still after CODE_SIGNING_ALLOWED, and
    // still before post_install's own `end`, so position alone proves nothing.
    // What gives it away is what follows: correctly placed, the only thing
    // left is post_install's `end`; nested, the loops' `end`s trail behind it.
    const after = updated.slice(updated.indexOf('# <<< getfit: pod deployment targets'));
    const remaining = after
      .split('\n')
      .slice(1)
      .map((line) => line.trimEnd())
      .filter((line) => line !== '');

    assert.equal(
      remaining[0],
      '  end',
      `post_install should close straight after the hook, found: ${remaining.slice(0, 4).join(' / ')}`,
    );
  });

  test('the hook runs once, not once per resource bundle', () => {
    // Nested inside the code-signing loop it executes for every configuration
    // of every bundle, saving the project each time.
    const between = updated.slice(
      updated.indexOf('post_install do |installer|'),
      updated.indexOf('# >>> getfit: pod deployment targets'),
    );
    const opened = (between.match(/\bdo \|/g) ?? []).length;
    const closed = (between.match(/^\s*end\s*$/gm) ?? []).length;
    // Exactly one block open at the injection point: post_install itself.
    assert.equal(
      opened - closed,
      1,
      `${opened - closed} blocks are open where the hook was injected, expected only post_install`,
    );
  });

  test('post_integrate is left alone', () => {
    assert.ok(lineOf(updated, 'getfit_minimum') < lineOf(updated, 'post_integrate'));
    assert.match(updated, /expo_patch_react_imports!/);
  });

  test('nothing else in the Podfile is disturbed', () => {
    for (const line of PODFILE.split('\n').filter(Boolean)) {
      assert.ok(updated.includes(line), `lost: ${line}`);
    }
  });

  test('the block closes as many times as it opens', () => {
    const body = withDeploymentTargetHook(PODFILE, '15.1');
    const opens = (body.match(/\bdo \|/g) ?? []).length + (body.match(/^\s*if /gm) ?? []).length;
    const ends = (body.match(/^\s*end\b/gm) ?? []).length;
    assert.ok(ends >= opens, `${opens} blocks opened, ${ends} ends`);
  });
});

describe('running prebuild twice', () => {
  test('leaves one hook, not two', () => {
    const once = withDeploymentTargetHook(PODFILE, '15.1');
    const twice = withDeploymentTargetHook(once, '15.1');
    assert.equal((twice.match(/getfit_minimum = /g) ?? []).length, 1);
    assert.equal(twice, once, 'a second prebuild should be a no-op');
  });

  test('a changed target replaces the old hook rather than adding one', () => {
    const once = withDeploymentTargetHook(PODFILE, '14.0');
    const twice = withDeploymentTargetHook(once, '15.1');
    assert.equal((twice.match(/getfit_minimum = /g) ?? []).length, 1);
    assert.match(twice, /getfit_minimum = '15\.1'/);
    assert.doesNotMatch(twice, /14\.0/);
  });
});

describe('what the hook carries', () => {
  const updated = withDeploymentTargetHook(PODFILE, '15.1');

  test('it raises rather than sets, so a newer pod keeps its own floor', () => {
    assert.match(updated, /Gem::Version\.new\(current\.to_s\) < Gem::Version\.new\(getfit_minimum\)/);
  });

  test('it walks targets, which is what includes resource bundles', () => {
    // pod_targets is the dependency graph; resource bundles are not in it.
    assert.match(updated, /project\.targets\.each/);
    assert.doesNotMatch(updated, /installer\.pod_targets\b/);
  });

  test('it covers CocoaPods versions with and without generated_projects', () => {
    assert.match(updated, /respond_to\?\(:generated_projects\)/);
    assert.match(updated, /installer\.pods_project/);
  });
});

describe('a Podfile it cannot safely edit', () => {
  test('no post_install is an error, not a silent skip', () => {
    const none = PODFILE.replace(/ {2}post_install do \|installer\|[\s\S]*?\n {2}end\n/, '');
    assert.throws(() => withDeploymentTargetHook(none, '15.1'), /post_install/);
  });

  test('an unclosed block is an error', () => {
    const broken = "target 'GetFit' do\n  post_install do |installer|\n    puts 1\n";
    assert.throws(() => withDeploymentTargetHook(broken, '15.1'), /never closed|post_install/);
  });
});

describe('reading the target from the Expo config', () => {
  test('takes it from expo-build-properties, the one place it is set', () => {
    const config = {
      plugins: ['expo-secure-store', ['expo-build-properties', { ios: { deploymentTarget: '15.1' } }]],
    };
    assert.equal(configuredTarget(config), '15.1');
  });

  test('returns null when the plugin is absent, so the caller can refuse', () => {
    assert.equal(configuredTarget({ plugins: ['expo-secure-store'] }), null);
    assert.equal(configuredTarget({}), null);
  });

  test('ignores expo-build-properties configured for Android only', () => {
    const config = { plugins: [['expo-build-properties', { android: { minSdkVersion: 24 } }]] };
    assert.equal(configuredTarget(config), null);
  });
});
