/**
 * The translation between documents and rows.
 *
 * The test that matters is the round trip: push a document up, pull it back,
 * and the app must not be able to tell. Anything this layer drops is data the
 * user loses the first time they open the app on a new phone.
 */
import assert from 'node:assert/strict';
import { describe, test } from 'node:test';
import { emptyProfile, type ProfileDocument, type ProgramDocument, type WorkoutsDocument, type AssessmentsDocument } from '../src/local/documents';
import {
  assessmentsDocToRows,
  goalId,
  profileDocToRows,
  programDocToRows,
  recordId,
  rowsToAssessmentsDoc,
  rowsToProfileDoc,
  rowsToProgramDoc,
  rowsToWorkoutsDoc,
  toIso,
  workoutsDocToRows,
} from '../src/supabase/rows';

const USER = '11111111-1111-1111-1111-111111111111';

const profileDoc = (): ProfileDocument => ({
  ...emptyProfile('user_local', '2026-01-01T00:00:00.000Z'),
  profile: {
    userId: 'user_local',
    age: 34,
    sex: 'female',
    heightCm: 168,
    weightKg: 62.5,
    trainingLevel: 'beginner',
    trainingLocation: 'home',
    trainingDays: 3,
    sessionDurationMinutes: 45,
    onboardingCompleted: true,
  },
  goals: [{ goalType: 'fat_loss', targetValue: 22, targetUnit: '%', isActive: true }],
  equipment: ['dumbbells', 'resistance_bands'],
  preferences: [{ muscleGroup: 'chest', exerciseIds: ['push_up'], autoGenerated: false }],
  preferencesChosen: true,
  settings: { themeMode: 'light', reducedMotion: true, units: 'imperial' },
});

describe('the profile survives a round trip', () => {
  test('every field comes back', () => {
    const original = profileDoc();
    const back = rowsToProfileDoc(profileDocToRows(USER, original));

    assert.equal(back.profile?.age, 34);
    assert.equal(back.profile?.sex, 'female');
    assert.equal(back.profile?.heightCm, 168);
    assert.equal(back.profile?.weightKg, 62.5);
    assert.equal(back.profile?.trainingLevel, 'beginner');
    assert.equal(back.profile?.trainingLocation, 'home');
    assert.equal(back.profile?.trainingDays, 3);
    assert.equal(back.profile?.sessionDurationMinutes, 45);
    assert.equal(back.profile?.onboardingCompleted, true);
  });

  test('settings the user chose are not quietly reset', () => {
    const back = rowsToProfileDoc(profileDocToRows(USER, profileDoc()));
    assert.deepEqual(back.settings, { themeMode: 'light', reducedMotion: true, units: 'imperial' });
    assert.equal(back.preferencesChosen, true);
  });

  test('goals, equipment and exercise choices come back', () => {
    const back = rowsToProfileDoc(profileDocToRows(USER, profileDoc()));
    assert.deepEqual(back.equipment, ['dumbbells', 'resistance_bands']);
    assert.equal(back.goals[0]?.goalType, 'fat_loss');
    assert.equal(back.goals[0]?.targetValue, 22);
    assert.deepEqual(back.preferences[0]?.exerciseIds, ['push_up']);
    assert.equal(back.preferences[0]?.autoGenerated, false);
  });

  test('the device id rides along, so history keeps pointing at the same person', () => {
    const back = rowsToProfileDoc(profileDocToRows(USER, profileDoc()));
    assert.equal(back.userId, 'user_local');
  });

  test('a half-finished onboarding does not come back as a usable profile', () => {
    // Letting a profile with nulls through would hand the programme generator
    // a height of zero.
    const partial = emptyProfile('user_local', '2026-01-01T00:00:00.000Z');
    const back = rowsToProfileDoc(profileDocToRows(USER, partial));
    assert.equal(back.profile, null);
  });
});

describe('the programme survives a round trip', () => {
  const programDoc = (): ProgramDocument => ({
    program: {
      id: 'program_1',
      userId: 'user_local',
      version: 2,
      splitName: 'Upper/Lower',
      trainingDays: 4,
      sessionDurationMinutes: 60,
      isActive: true,
      days: [
        {
          id: 'day_1',
          dayNumber: 1,
          focus: 'Upper',
          durationMinutes: 60,
          exercises: [{ exerciseId: 'bench_press', sets: 3 }],
          cardio: null,
        },
      ],
      volumeSummary: { chest: { direct: 9, secondary: 3, effective: 12 } },
    } as unknown as ProgramDocument['program'],
    schedule: [
      {
        id: 'slot_1',
        programDayId: 'day_1',
        dayNumber: 1,
        focus: 'Upper',
        scheduledDate: '2026-09-24',
        status: 'scheduled',
        durationMinutes: 60,
        completedWorkoutId: null,
      },
    ],
  });

  test('the nested plan is not flattened or trimmed', () => {
    const back = rowsToProgramDoc(programDocToRows(USER, programDoc()), 'user_local');
    assert.equal(back.program?.splitName, 'Upper/Lower');
    assert.equal(back.program?.days[0]?.exercises.length, 1);
    assert.deepEqual(back.program?.volumeSummary, {
      chest: { direct: 9, secondary: 3, effective: 12 },
    });
  });

  test('a scheduled date stays the plain day the schedule compares on', () => {
    // todaysWorkout() compares these as strings against YYYY-MM-DD. A timestamp
    // here would silently stop matching.
    const back = rowsToProgramDoc(programDocToRows(USER, programDoc()), 'user_local');
    assert.equal(back.schedule[0]?.scheduledDate, '2026-09-24');
  });
});

describe('workouts and records survive a round trip', () => {
  const workoutsDoc = (): WorkoutsDocument => ({
    completed: [
      {
        id: 'workout_1',
        userId: 'user_local',
        programDayId: 'day_1',
        dayNumber: 1,
        focus: 'Upper',
        startedAt: '2026-09-20T10:00:00.000Z',
        completedAt: '2026-09-20T11:05:00.000Z',
        durationSeconds: 3900,
        totalSets: 18,
        totalVolumeKg: 6420.5,
        cardioMinutes: 10,
        exercises: [
          {
            exerciseId: 'bench_press',
            orderIndex: 0,
            sets: [
              {
                setNumber: 1,
                actualWeight: 60,
                actualReps: 8,
                prescribedWeight: 60,
                prescribedRepsMin: 6,
                prescribedRepsMax: 10,
                isWarmup: false,
                completedAt: '2026-09-20T10:10:00.000Z',
              },
            ],
          },
        ],
        personalRecords: [
          {
            exerciseId: 'bench_press',
            recordType: 'weight',
            value: 60,
            previousValue: 55,
            achievedAt: '2026-09-20T10:10:00.000Z',
          },
        ],
      },
    ] as WorkoutsDocument['completed'],
    records: [
      {
        exerciseId: 'bench_press',
        recordType: 'weight',
        value: 60,
        previousValue: 55,
        achievedAt: '2026-09-20T10:10:00.000Z',
      },
    ],
  });

  test('every logged set comes back', () => {
    const back = rowsToWorkoutsDoc(workoutsDocToRows(USER, workoutsDoc()), 'user_local');
    const sets = back.completed[0]?.exercises[0]?.sets ?? [];
    assert.equal(sets.length, 1);
    assert.equal(sets[0]?.actualWeight, 60);
    assert.equal(sets[0]?.actualReps, 8);
  });

  test('the records set during a workout stay with it', () => {
    const back = rowsToWorkoutsDoc(workoutsDocToRows(USER, workoutsDoc()), 'user_local');
    assert.equal(back.completed[0]?.personalRecords.length, 1);
  });

  test('volume is not rounded away', () => {
    const back = rowsToWorkoutsDoc(workoutsDocToRows(USER, workoutsDoc()), 'user_local');
    assert.equal(back.completed[0]?.totalVolumeKg, 6420.5);
  });

  test('a record with no id gets one that is the same every push', () => {
    const doc = workoutsDoc();
    const first = workoutsDocToRows(USER, doc).records[0]?.id;
    const second = workoutsDocToRows(USER, doc).records[0]?.id;
    assert.equal(first, second);
    assert.ok(first?.includes('bench_press'));
  });
});

describe('assessments survive a round trip', () => {
  const assessmentsDoc = (): AssessmentsDocument => ({
    assessments: [
      {
        id: 'assessment_1',
        userId: 'user_local',
        createdAt: '2026-09-01T08:00:00.000Z',
        weightKg: 62.5,
        assessmentNumber: 1,
        sourcePhotoId: 'file:///var/mobile/photo.jpg',
        measurements: { waistCm: 74, neckCm: 32, hipCm: 96 },
        bodyFatPercent: 26.4,
        estimatedMuscleMassKg: 28.1,
        waistBodyRatio: 0.44,
        symmetryPercent: null,
        method: 'navy',
        confidence: 0.75,
        hologramData: { seed: 7 },
        provider: 'local',
      },
    ] as unknown as AssessmentsDocument['assessments'],
  });

  test('the figures come back exactly', () => {
    const back = rowsToAssessmentsDoc(assessmentsDocToRows(USER, assessmentsDoc()), 'user_local');
    const first = back.assessments[0];
    assert.equal(first?.bodyFatPercent, 26.4);
    assert.equal(first?.estimatedMuscleMassKg, 28.1);
    assert.equal(first?.waistBodyRatio, 0.44);
    assert.equal(first?.confidence, 0.75);
    assert.deepEqual(first?.measurements, { waistCm: 74, neckCm: 32, hipCm: 96 });
  });

  test('a missing symmetry reading stays missing rather than becoming zero', () => {
    const back = rowsToAssessmentsDoc(assessmentsDocToRows(USER, assessmentsDoc()), 'user_local');
    assert.equal(back.assessments[0]?.symmetryPercent, null);
  });

  test('the photo path is never uploaded', () => {
    const rows = assessmentsDocToRows(USER, assessmentsDoc());
    const serialised = JSON.stringify(rows);
    assert.ok(!serialised.includes('photo.jpg'), 'a photo path reached the server');
    assert.ok(!serialised.includes('sourcePhotoId'));
    assert.ok(!serialised.includes('source_photo_id'));
  });

  test('pulled on a new phone there is no photo to point at', () => {
    const back = rowsToAssessmentsDoc(assessmentsDocToRows(USER, assessmentsDoc()), 'user_local');
    assert.equal(back.assessments[0]?.sourcePhotoId, null);
  });
});

describe('shapes that come back from Postgres rather than the device', () => {
  test('a timestamp in Postgres’ own format is normalised', () => {
    assert.equal(toIso('2026-09-23T10:00:00+00:00'), '2026-09-23T10:00:00.000Z');
  });

  test('a numeric handed back as a string still behaves like a number', () => {
    const back = rowsToWorkoutsDoc(
      {
        completed: [],
        records: [
          {
            user_id: USER,
            id: 'pr_1',
            exercise_id: 'squat',
            record_type: 'weight',
            value: '102.50' as unknown as number,
            previous_value: '100' as unknown as number,
            achieved_at: '2026-09-20T10:00:00+00:00',
          },
        ],
      },
      'user_local',
    );

    assert.equal(back.records[0]?.value, 102.5);
    assert.equal(back.records[0]?.previousValue, 100);
  });

  test('a jsonb column that arrives null does not crash a screen', () => {
    const back = rowsToWorkoutsDoc(
      {
        completed: [
          {
            user_id: USER,
            id: 'workout_1',
            program_day_id: null,
            day_number: 1,
            focus: 'Upper',
            started_at: '2026-09-20T10:00:00+00:00',
            completed_at: '2026-09-20T11:00:00+00:00',
            duration_seconds: 3600,
            total_sets: 10,
            total_volume_kg: 100,
            cardio_minutes: 0,
            exercises: null as never,
            personal_records: null as never,
          },
        ],
        records: [],
      },
      'user_local',
    );

    assert.deepEqual(back.completed[0]?.exercises, []);
    assert.deepEqual(back.completed[0]?.personalRecords, []);
  });
});

describe('ids for records the local model never named', () => {
  test('a goal keeps one id per type, so pushing twice does not duplicate it', () => {
    assert.equal(goalId({ goalType: 'muscle_gain' }), 'goal_muscle_gain');
  });

  test('an id the device already assigned is kept', () => {
    assert.equal(goalId({ id: 'goal_abc', goalType: 'muscle_gain' }), 'goal_abc');
    assert.equal(
      recordId({
        id: 'pr_abc',
        exerciseId: 'squat',
        recordType: 'weight',
        value: 1,
        previousValue: null,
        achievedAt: '2026-01-01T00:00:00.000Z',
      }),
      'pr_abc',
    );
  });
});
